# -*- coding: utf-8 -*-
"""Optimal 50_subgroups.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yOXw4R5Xeol5Zqe24S3oykTK6wBKcO6H
"""



# ============================================================
# 50 Paddy practices: synthesize data + GRASP + warm-start MILP
# + NEW: "At most ONE (or NONE) practice from each REAL subgroup"
#   (Water / Establishment / Nitrogen / Residue / Soil)
# Dense mixed-sign pairwise interactions (alpha, delta, gamma)
# ============================================================

from __future__ import annotations
import os, random
from dataclasses import dataclass
from itertools import combinations
from typing import Dict, List, Tuple, Set

import pandas as pd

# -----------------------------
# Your 50 practices (exact list)
# -----------------------------
PRACTICES = [
    "Alternate Wetting and Drying (AWD)",
    "AWD using field water-tube monitoring (measured thresholds)",
    "AWD with fewer flooding days (reduced continuous inundation)",
    "Mid-season drainage (MSD)",
    "Early-season drainage (shorten initial flooding period)",
    "Pre-harvest drainage (timely drainage before harvest)",
    "Intermittent irrigation scheduling (fixed wet–dry cycles)",
    "Improved drainage outlets (faster drawdown)",
    "Bund repair + leveling to enable controlled AWD (enables water control)",
    "Laser land leveling (supports uniform AWD / less waterlogging)",
    "Raised beds / furrow-irrigated rice (where applicable)",
    "Aerobic rice management (non-flooded rice system)",
    "Conversion of long-duration flooded rice to shorter-duration rice (less flooding time)",
    "Use of short-duration varieties to reduce flooded period",
    "Shift from transplanted puddled rice to systems reducing puddling/flooding duration (where defined)",
    "Direct-Seeded Rice (DSR) (reduces flooded nursery/puddling period)",
    "Dry seeding (non-puddled establishment)",
    "Reduced puddling intensity (where permitted/defined)",
    "Strip till / reduced till rice establishment (where feasible)",
    "Controlled traffic / minimized soil disturbance (site-dependent)",
    "Improved field channels for precise irrigation (enables AWD)",
    "Timely weeding to maintain aerobic periods (supports AWD feasibility)",
    "Mechanized operations reducing repeated puddling passes (site-dependent)",
    "Optimized N rate (reduce excess N)",
    "Split N application (better timing reduces losses)",
    "Deep placement of urea (UDP)",
    "Controlled-release urea (CRU)",
    "Nitrification inhibitors (where allowed)",
    "Urease inhibitors (where allowed)",
    "Site-Specific Nutrient Management (SSNM)",
    "Leaf Color Chart (LCC)-guided N dosing",
    "Basal N reduction with more top-dressing precision",
    "Balanced fertilization (adequate P/K to reduce excess N needs)",
    "Avoid N application just before heavy irrigation/rain (timing rule)",
    "Replace part of urea with organic sources under planned rates (avoid over-application)",
    "Precision fertilizer application (band placement, calibrated applicators)",
    "Improved manure management timing (avoid anaerobic + N surplus conditions)",
    "Inclusion of legumes in rotation where feasible (reduces synthetic N demand)",
    "No open-field burning of rice straw (avoided emissions)",
    "Straw removal + off-field productive use (with leakage accounted)",
    "Straw composting (instead of burning)",
    "Straw incorporation with drainage/timing to reduce methane spikes (managed incorporation)",
    "Straw mulching under non-flooded/managed water (method-dependent)",
    "Use of straw for bioenergy with accounting (project/method dependent)",
    "Collection/baling systems to prevent burning (enabler for #39)",
    "Biochar application (rice husk/straw biochar)",
    "Compost application (stabilized organic matter)",
    "Farmyard manure application under monitored rates (SOC improvement; method-dependent)",
    "Green manuring (e.g., Sesbania/dhaincha) with proper water management (SOC + N dynamics)",
    "Cover crop/legume in rice fallow (where feasible) to build SOC (rotation-based crediting)",
]

# -----------------------------
# Parameters you can edit
# -----------------------------
SEED = 7

# Economic parameters
CCP = 1200.0        # INR per tCO2e
CROP_PRICE = 22.0   # INR per kg

# GRASP settings
GRASP_ITERS = 250
ALPHA_RCL = 0.30
P_EXPLORE = 0.12

# MILP settings
MILP_TIME_LIMIT_SEC = 60  # set None for no limit
USE_WARMSTART = True

# Output folder for CSVs
OUT_DIR = "synthetic_bundle_50"

# -----------------------------
# NEW: Real "subgroups" (your headings) — at most 1 per subgroup
# Indices are 0-based:
#  1-15  -> 0..14
# 16-23  -> 15..22
# 24-38  -> 23..37
# 39-45  -> 38..44
# 46-50  -> 45..49
# -----------------------------
REAL_GROUPS = {
    "water_methane": list(range(0, 15)),
    "establishment_ops": list(range(15, 23)),
    "nitrogen": list(range(23, 38)),
    "residue": list(range(38, 45)),
    "soil_carbon": list(range(45, 50)),
}

def build_subgroup_of(n: int) -> Tuple[List[int], List[str]]:
    """Returns subgroup_of[i] = group_id in [0..G-1] and group_names list."""
    group_names = list(REAL_GROUPS.keys())
    subgroup_of = [-1] * n
    for gid, gname in enumerate(group_names):
        for i in REAL_GROUPS[gname]:
            if 0 <= i < n:
                subgroup_of[i] = gid
    if any(g == -1 for g in subgroup_of):
        raise ValueError("Some practices were not assigned to a REAL_GROUP. Check index ranges.")
    return subgroup_of, group_names


# ============================================================
# 1) Categorization + (optional) extra exclusivity (for synthetic incompatibilities)
# ============================================================
def classify_practice(name: str) -> Tuple[str, str]:
    s = name.lower()

    # Categories (broad)
    if any(k in s for k in ["awd", "drain", "irrig", "flood", "bund", "laser", "raised beds", "furrow", "aerobic", "channel"]):
        cat = "water"
    elif any(k in s for k in ["direct-seeded", "dsr", "dry seeding", "puddling", "strip till", "reduced till", "controlled traffic", "mechanized", "weeding"]):
        cat = "establishment"
    elif any(k in s for k in ["n rate", "split", "urea", "udp", "cru", "inhibitor", "ssnm", "lcc", "fertiliz", "manure", "legume", "precision fertilizer"]):
        cat = "nitrogen"
    elif any(k in s for k in ["straw", "burn", "mulch", "composting", "bioenergy", "baling", "incorporation"]):
        cat = "residue"
    elif any(k in s for k in ["biochar", "farmyard manure", "green manuring", "cover crop", "soc", "stabilized organic"]):
        cat = "soil"
    else:
        cat = "general"

    # Optional fine exclusivity groups (these create extra incompatibilities in synthetic data)
    ex = ""
    if "awd" in s:
        ex = "awd_variant"
    if any(k in s for k in ["direct-seeded", "dsr", "dry seeding", "reduced puddling", "strip till", "reduced till",
                            "shift from transplanted", "transplanted puddled", "non-puddled"]):
        ex = "establishment_method"
    if any(k in s for k in ["aerobic rice", "raised beds", "furrow-irrigated"]):
        ex = "aerobic_regime"
    if "short-duration" in s or "long-duration" in s:
        ex = "duration_choice"
    if "straw" in s or "burn" in s or "bioenergy" in s or "baling" in s:
        ex = "residue_fate"

    return cat, ex


BASE_RANGES = {
    "water":        {"CSP": (0.9, 2.8), "DY": (-140, 240), "OC": (500, 3800)},
    "establishment":{"CSP": (0.3, 1.6), "DY": (-60, 260),  "OC": (600, 4200)},
    "nitrogen":     {"CSP": (0.1, 0.9), "DY": (20, 240),   "OC": (600, 5200)},
    "residue":      {"CSP": (0.4, 1.8), "DY": (-80, 180),  "OC": (400, 3800)},
    "soil":         {"CSP": (0.8, 3.0), "DY": (-20, 220),  "OC": (800, 6500)},
    "general":      {"CSP": (0.2, 1.0), "DY": (-40, 180),  "OC": (700, 4000)},
}

def tri(rng: random.Random, lo: float, hi: float, mode_frac: float) -> float:
    mode = lo + mode_frac * (hi - lo)
    return rng.triangular(lo, hi, mode)

def pair_key(i: int, j: int) -> Tuple[int, int]:
    return (i, j) if i < j else (j, i)


# ============================================================
# 2) Synthetic generation
# ============================================================
@dataclass
class BundleData:
    ids: List[str]
    cats: List[str]
    ex_groups: List[str]
    CSP: List[float]
    OC: List[float]
    DY: List[float]
    alpha: Dict[Tuple[int,int], float]
    delta: Dict[Tuple[int,int], float]
    gamma: Dict[Tuple[int,int], float]
    incompat_idx: List[Tuple[int,int]]

def generate_data(practices: List[str], seed: int, out_dir: str) -> BundleData:
    rng = random.Random(seed)
    ids = practices[:]
    n = len(ids)

    cats, ex_groups = [], []
    for nm in ids:
        c, ex = classify_practice(nm)
        cats.append(c)
        ex_groups.append(ex)

    CSP, OC, DY = [], [], []
    for i in range(n):
        r = BASE_RANGES.get(cats[i], BASE_RANGES["general"])
        csp = tri(rng, *r["CSP"], mode_frac=0.62)
        dy  = tri(rng, *r["DY"],  mode_frac=0.55)
        oc  = tri(rng, *r["OC"],  mode_frac=0.58)

        s = ids[i].lower()

        if cats[i] == "water":
            if any(k in s for k in ["drain", "awd", "aerobic"]):
                dy += rng.uniform(-50, 30)
            if "laser" in s:
                oc += rng.uniform(1200, 2200)
                dy += rng.uniform(20, 80)

        if cats[i] == "nitrogen":
            if any(k in s for k in ["inhibitor", "controlled-release", "cru", "udp", "deep placement"]):
                oc += rng.uniform(900, 2200)
                dy += rng.uniform(0, 40)
            if any(k in s for k in ["lcc", "ssnm", "precision"]):
                dy += rng.uniform(10, 60)

        if cats[i] == "residue":
            if "no open-field burning" in s:
                oc += rng.uniform(200, 800)
            if "incorporation" in s:
                dy += rng.uniform(-40, 40)
            if "compost" in s:
                dy += rng.uniform(10, 60)

        if cats[i] == "soil":
            if "biochar" in s:
                oc += rng.uniform(1500, 3500)
                csp += rng.uniform(0.3, 0.9)
                dy += rng.uniform(0, 60)
            if "cover crop" in s or "green manuring" in s:
                oc += rng.uniform(500, 1400)
                csp += rng.uniform(0.2, 0.6)

        csp = max(0.02, min(3.5, csp))
        dy  = max(-400.0, min(600.0, dy))
        oc  = max(150.0, min(9000.0, oc))

        CSP.append(round(csp, 4))
        DY.append(round(dy, 2))
        OC.append(round(oc, 2))

    complementary = {
        ("water", "nitrogen"), ("water", "residue"), ("water", "soil"),
        ("nitrogen", "soil"), ("residue", "soil"), ("establishment", "water"),
        ("establishment", "nitrogen"),
    }
    def is_comp(a: str, b: str) -> bool:
        return (a, b) in complementary or (b, a) in complementary

    alpha: Dict[Tuple[int,int], float] = {}
    delta: Dict[Tuple[int,int], float] = {}
    gamma: Dict[Tuple[int,int], float] = {}

    for i, j in combinations(range(n), 2):
        same = (cats[i] == cats[j])
        comp = is_comp(cats[i], cats[j])

        mu = (0.30 if comp else 0.0) + (-0.22 if same else 0.0)
        z1 = rng.gauss(mu, 0.50)
        z2 = rng.gauss(mu, 0.70)
        z3 = rng.gauss((0.18 if same else 0.0) + (-0.08 if comp else 0.0), 0.38)

        a = (0.25 * min(CSP[i], CSP[j])) * z1
        a = max(-0.80, min(1.00, a))
        alpha[(i, j)] = round(a, 4)

        base_y = min(max(abs(DY[i]), 70.0), max(abs(DY[j]), 70.0), 280.0)
        d = (0.25 * base_y) * z2
        d = max(-220.0, min(260.0, d))
        delta[(i, j)] = round(d, 2)

        g = (0.20 * min(OC[i], OC[j])) * z3
        g = max(-1000.0, min(2200.0, g))
        gamma[(i, j)] = round(g, 2)

    incompat: Set[Tuple[int,int]] = set()

    # A) extra exclusivity (optional, mostly redundant once we enforce REAL_GROUPS <=1)
    group_to_items: Dict[str, List[int]] = {}
    for idx, g in enumerate(ex_groups):
        if g:
            group_to_items.setdefault(g, []).append(idx)
    for g, items in group_to_items.items():
        if len(items) >= 2:
            for i, j in combinations(items, 2):
                incompat.add(pair_key(i, j))

    # B) extra hard-conflict pairs (small %)
    all_pairs = list(combinations(range(n), 2))
    def conflict_score(i: int, j: int) -> float:
        a = alpha[(i, j)]
        d = delta[(i, j)] / 200.0
        g = gamma[(i, j)] / 1500.0
        return a + d - g

    ranked = sorted(all_pairs, key=lambda p: conflict_score(p[0], p[1]))
    target_extra = int(0.05 * len(all_pairs))
    added = 0
    for (i, j) in ranked:
        if added >= target_extra:
            break
        if (i, j) in incompat:
            continue
        if conflict_score(i, j) < -0.60:
            incompat.add((i, j))
            added += 1

    incompat_idx = sorted(incompat)

    os.makedirs(out_dir, exist_ok=True)

    df_pr = pd.DataFrame({
        "idx": list(range(n)),
        "practice": ids,
        "category": cats,
        "exclusive_group": ex_groups,
        "CSP_tCO2e": CSP,
        "OC_INR": OC,
        "dY_kg_per_ha": DY,
    })
    df_pr.to_csv(os.path.join(out_dir, "practices.csv"), index=False)

    df_int = pd.DataFrame([
        {"i": i, "j": j, "alpha": alpha[(i, j)], "delta": delta[(i, j)], "gamma": gamma[(i, j)]}
        for (i, j) in all_pairs
    ])
    df_int.to_csv(os.path.join(out_dir, "interactions.csv"), index=False)

    df_inc = pd.DataFrame([{"i": i, "j": j} for (i, j) in incompat_idx])
    df_inc.to_csv(os.path.join(out_dir, "incompatibilities.csv"), index=False)

    print(f"[OK] Wrote: {out_dir}/practices.csv, interactions.csv, incompatibilities.csv")
    print(f"n={n}, pairs={len(all_pairs)}, incompatibilities={len(incompat_idx)}")
    print("CSP range:", (min(CSP), max(CSP)), "tCO2e")
    print("DY  range:", (min(DY), max(DY)), "kg/ha")
    print("OC  range:", (min(OC), max(OC)), "INR")

    return BundleData(
        ids=ids, cats=cats, ex_groups=ex_groups,
        CSP=CSP, OC=OC, DY=DY,
        alpha=alpha, delta=delta, gamma=gamma,
        incompat_idx=incompat_idx
    )


# ============================================================
# 3) Build objective coefficients
# ============================================================
def build_objective(data: BundleData, CCP: float, CROP_PRICE: float):
    n = len(data.ids)
    b = [CCP * data.CSP[i] + CROP_PRICE * data.DY[i] - data.OC[i] for i in range(n)]

    w = [[0.0] * n for _ in range(n)]
    gmat = [[0.0] * n for _ in range(n)]
    for (i, j), a in data.alpha.items():
        d = data.delta[(i, j)]
        g = data.gamma[(i, j)]
        wij = CCP * a + CROP_PRICE * d - g
        w[i][j] = w[j][i] = float(wij)
        gmat[i][j] = gmat[j][i] = float(g)
    return b, w, gmat


# ============================================================
# 4) GRASP with NEW subgroup constraint (<= 1 per REAL_GROUP)
# ============================================================
def build_incompat_sets(n: int, incompat_idx: List[Tuple[int,int]]) -> List[Set[int]]:
    inc = [set() for _ in range(n)]
    for i, j in incompat_idx:
        inc[i].add(j)
        inc[j].add(i)
    return inc

def grasp_solve(n: int, b: List[float], w: List[List[float]], OC: List[float], gmat: List[List[float]],
                incompat: List[Set[int]], B: float,
                subgroup_of: List[int], num_groups: int,
                iters: int = 200, alpha_rcl: float = 0.3, p_explore: float = 0.10, seed: int = 0):
    rng = random.Random(seed)

    def construct_once():
        inS = [False]*n
        group_taken = [False]*num_groups

        S = []
        sumW = [0.0]*n
        sumG = [0.0]*n
        cur_val = 0.0
        cur_cost = 0.0

        while True:
            cand = []
            for i in range(n):
                if inS[i]:
                    continue

                gi = subgroup_of[i]
                if group_taken[gi]:
                    continue

                if any(inS[j] for j in incompat[i]):
                    continue

                add_cost = OC[i] + sumG[i]
                if cur_cost + add_cost > B + 1e-9:
                    continue

                add_gain = b[i] + sumW[i]
                score = add_gain / max(add_cost, 1.0)
                cand.append((i, score, add_gain, add_cost))

            if not cand:
                break

            pos = [c for c in cand if c[2] > 1e-9]
            if pos:
                pool = pos
            else:
                if rng.random() > p_explore:
                    break
                pool = cand

            scores = [c[1] for c in pool]
            smax, smin = max(scores), min(scores)
            cutoff = smax - alpha_rcl*(smax - smin)
            rcl = [c for c in pool if c[1] >= cutoff]
            i = rng.choice(rcl)[0]

            # add i
            inS[i] = True
            group_taken[subgroup_of[i]] = True
            S.append(i)

            cur_val += b[i] + sumW[i]
            cur_cost += OC[i] + sumG[i]

            for k in range(n):
                if k == i:
                    continue
                sumW[k] += w[k][i]
                sumG[k] += gmat[k][i]

        return S

    def local_search(S0: List[int]):
        inS = [False]*n
        group_taken = [False]*num_groups
        for i in S0:
            inS[i] = True
            group_taken[subgroup_of[i]] = True

        sumW = [0.0]*n
        sumG = [0.0]*n
        cur_val = 0.0
        cur_cost = 0.0

        for i in range(n):
            if inS[i]:
                cur_val += b[i]
                cur_cost += OC[i]

        for i, j in combinations(range(n), 2):
            if inS[i] and inS[j]:
                cur_val += w[i][j]
                cur_cost += gmat[i][j]

        for i in range(n):
            sw = 0.0
            sg = 0.0
            for j in range(n):
                if inS[j] and j != i:
                    sw += w[i][j]
                    sg += gmat[i][j]
            sumW[i] = sw
            sumG[i] = sg

        def feasible_add(x: int) -> bool:
            if inS[x]:
                return False
            gx = subgroup_of[x]
            if group_taken[gx]:
                return False
            if any(inS[j] for j in incompat[x]):
                return False
            return cur_cost + (OC[x] + sumG[x]) <= B + 1e-9

        improved = True
        while improved:
            improved = False
            best_gain = 0.0
            best_move = None

            # ADD
            for j in range(n):
                if feasible_add(j):
                    gain = b[j] + sumW[j]
                    if gain > best_gain + 1e-9:
                        best_gain = gain
                        best_move = ("add", j)

            # REMOVE
            for i in range(n):
                if inS[i]:
                    gain = -(b[i] + sumW[i])
                    if gain > best_gain + 1e-9:
                        best_gain = gain
                        best_move = ("rem", i)

            # SWAP
            for i in range(n):
                if not inS[i]:
                    continue
                gi = subgroup_of[i]
                cost_after_rem = cur_cost - (OC[i] + sumG[i])

                for j in range(n):
                    if inS[j]:
                        continue

                    gj = subgroup_of[j]
                    # after removing i, group gi becomes free; allow adding j if:
                    # - gj is free, OR gj == gi (because i is removed)
                    if group_taken[gj] and gj != gi:
                        continue

                    # incompat check against S\{i}
                    bad = False
                    for k in incompat[j]:
                        if inS[k] and k != i:
                            bad = True
                            break
                    if bad:
                        continue

                    add_cost_after = OC[j] + (sumG[j] - gmat[j][i])
                    if cost_after_rem + add_cost_after > B + 1e-9:
                        continue

                    add_gain_after = b[j] + (sumW[j] - w[j][i])
                    rem_gain = -(b[i] + sumW[i])
                    gain = rem_gain + add_gain_after
                    if gain > best_gain + 1e-9:
                        best_gain = gain
                        best_move = ("swap", i, j)

            if best_move is None:
                break

            improved = True

            def apply_remove(i: int):
                nonlocal cur_val, cur_cost
                inS[i] = False
                group_taken[subgroup_of[i]] = False

                cur_val -= b[i] + sumW[i]
                cur_cost -= OC[i] + sumG[i]

                for k in range(n):
                    if k == i:
                        continue
                    sumW[k] -= w[k][i]
                    sumG[k] -= gmat[k][i]

                sumW[i] = 0.0
                sumG[i] = 0.0

            def apply_add(j: int):
                nonlocal cur_val, cur_cost
                inS[j] = True
                group_taken[subgroup_of[j]] = True

                cur_val += b[j] + sumW[j]
                cur_cost += OC[j] + sumG[j]

                for k in range(n):
                    if k == j:
                        continue
                    sumW[k] += w[k][j]
                    sumG[k] += gmat[k][j]

                sw = 0.0
                sg = 0.0
                for k in range(n):
                    if inS[k] and k != j:
                        sw += w[j][k]
                        sg += gmat[j][k]
                sumW[j] = sw
                sumG[j] = sg

            typ = best_move[0]
            if typ == "add":
                apply_add(best_move[1])
            elif typ == "rem":
                apply_remove(best_move[1])
            else:
                i, j = best_move[1], best_move[2]
                apply_remove(i)
                apply_add(j)

        S_final = [i for i in range(n) if inS[i]]
        return S_final, cur_val, cur_cost

    best_S, best_val, best_cost = [], float("-inf"), 0.0
    for _ in range(iters):
        S0 = construct_once()
        S1, v1, c1 = local_search(S0)
        if v1 > best_val:
            best_S, best_val, best_cost = S1, v1, c1

    return best_S, best_val, best_cost


# ============================================================
# 5) MILP warm-started from GRASP + NEW subgroup constraints
#     Also: we only create y_ij for CROSS-SUBGROUP pairs (smaller MILP)
# ============================================================
def solve_milp(n: int, b: List[float], w: List[List[float]], OC: List[float], gmat: List[List[float]],
              incompat_idx: List[Tuple[int,int]], B: float, start_S: List[int] | None,
              subgroup_of: List[int], group_names: List[str],
              time_limit: int | None = None, warmstart: bool = True):
    try:
        import pulp
    except ImportError:
        import sys, subprocess
        subprocess.check_call([sys.executable, "-m", "pip", "install", "pulp"])
        import pulp

    prob = pulp.LpProblem("QKP_Bundle_Grouped", pulp.LpMaximize)

    x = {i: pulp.LpVariable(f"x_{i}", cat="Binary") for i in range(n)}

    # only cross-group pairs matter (within group cannot both be 1)
    pairs = [(i, j) for i in range(n) for j in range(i+1, n) if subgroup_of[i] != subgroup_of[j]]
    y = {(i, j): pulp.LpVariable(f"y_{i}_{j}", cat="Binary") for (i, j) in pairs}

    # objective
    prob += pulp.lpSum(b[i] * x[i] for i in range(n)) + pulp.lpSum(w[i][j] * y[(i, j)] for (i, j) in pairs)

    # incompatibilities (still allowed; many will be redundant now)
    for (i, j) in incompat_idx:
        prob += x[i] + x[j] <= 1

    # subgroup constraints: at most one from each REAL subgroup
    # build items per group id
    G = len(group_names)
    group_items = {gid: [] for gid in range(G)}
    for i in range(n):
        group_items[subgroup_of[i]].append(i)
    for gid, items in group_items.items():
        prob += pulp.lpSum(x[i] for i in items) <= 1

    # linearize y_ij = x_i * x_j for cross-group pairs
    for (i, j) in pairs:
        prob += y[(i, j)] <= x[i]
        prob += y[(i, j)] <= x[j]
        prob += y[(i, j)] >= x[i] + x[j] - 1

    # budget
    prob += pulp.lpSum(OC[i] * x[i] for i in range(n)) + pulp.lpSum(gmat[i][j] * y[(i, j)] for (i, j) in pairs) <= B

    # warm start
    if warmstart and start_S is not None:
        Sset = set(start_S)
        for i in range(n):
            x[i].setInitialValue(1 if i in Sset else 0)
        for (i, j) in pairs:
            y[(i, j)].setInitialValue(1 if (i in Sset and j in Sset) else 0)

    solver_kwargs = {"msg": False}
    if time_limit is not None:
        solver_kwargs["timeLimit"] = time_limit
    if warmstart:
        solver_kwargs["warmStart"] = True

    solver = pulp.PULP_CBC_CMD(**solver_kwargs)
    prob.solve(solver)

    status = pulp.LpStatus[prob.status]
    chosen = [i for i in range(n) if int(pulp.value(x[i])) == 1]
    obj = float(pulp.value(prob.objective))
    return status, chosen, obj


# ============================================================
# 6) Run everything
# ============================================================
data = generate_data(PRACTICES, seed=SEED, out_dir=OUT_DIR)
ids = data.ids
n = len(ids)

# NEW subgroup mapping
subgroup_of, group_names = build_subgroup_of(n)
print("\nREAL subgroups:", group_names)

b, w_obj, gmat = build_objective(data, CCP=CCP, CROP_PRICE=CROP_PRICE)

# incompatibilities (still used, but now most within-group ones are redundant)
incompat_sets = build_incompat_sets(n, data.incompat_idx)

# Budget (you set it)
BUDGET_INR = 3500
print("\nBUDGET_INR:", BUDGET_INR)

# --- GRASP (with subgroup constraint) ---
Sg, Vg, Cg = grasp_solve(
    n, b, w_obj, data.OC, gmat, incompat_sets, B=BUDGET_INR,
    subgroup_of=subgroup_of, num_groups=len(group_names),
    iters=GRASP_ITERS, alpha_rcl=ALPHA_RCL, p_explore=P_EXPLORE, seed=SEED
)

print("\n=== GRASP result (<=1 per subgroup) ===")
print("Selected:", len(Sg), "practices (max possible =", len(group_names), ")")
print("Cost:", round(Cg, 2), " / Budget:", round(BUDGET_INR, 2))
print("Objective:", round(Vg, 2))
print("Bundle:")
for i in sorted(Sg):
    print(f"  - ({i+1:02d}) [{group_names[subgroup_of[i]]}] {ids[i]}")

# --- MILP (warm-started from GRASP, with subgroup constraints) ---
status, Sm, Vm = solve_milp(
    n, b, w_obj, data.OC, gmat, data.incompat_idx, B=BUDGET_INR,
    start_S=Sg,
    subgroup_of=subgroup_of, group_names=group_names,
    time_limit=MILP_TIME_LIMIT_SEC, warmstart=USE_WARMSTART
)

print("\n=== MILP result (<=1 per subgroup, warm-started) ===")
print("Status:", status)
print("Selected:", len(Sm), "practices (max possible =", len(group_names), ")")
print("Objective:", round(Vm, 2))
print("Bundle:")
for i in sorted(Sm):
    print(f"  - ({i+1:02d}) [{group_names[subgroup_of[i]]}] {ids[i]}")

print("\nObjective gap (MILP - GRASP):", round(Vm - Vg, 6))

import time
import pandas as pd
import matplotlib.pyplot as plt

# ---- choose budgets to test (you can edit these) ----
budgets = [1500, 2000, 2500, 3000, 3500, 4500, 5500, 7000, 9000, 12000]

# GRASP robustness: multiple seeds, keep best
GRASP_SEEDS = [1, 7, 11, 21, 42]
GRASP_ITERS_LOCAL = 200

rows = []
for B in budgets:
    # ---------- GRASP (best-of-seeds) ----------
    t0 = time.perf_counter()
    best_Sg, best_Vg, best_Cg = [], float("-inf"), 0.0

    for sd in GRASP_SEEDS:
        Sg, Vg, Cg = grasp_solve(
            n, b, w_obj, data.OC, gmat, incompat_sets, B=B,
            subgroup_of=subgroup_of, num_groups=len(group_names),
            iters=GRASP_ITERS_LOCAL, alpha_rcl=ALPHA_RCL, p_explore=P_EXPLORE, seed=sd
        )
        if Vg > best_Vg:
            best_Sg, best_Vg, best_Cg = Sg, Vg, Cg

    grasp_time = time.perf_counter() - t0

    # ---------- MILP ----------
    t1 = time.perf_counter()
    status, Sm, Vm = solve_milp(
        n, b, w_obj, data.OC, gmat, data.incompat_idx, B=B,
        start_S=best_Sg,
        subgroup_of=subgroup_of, group_names=group_names,
        time_limit=MILP_TIME_LIMIT_SEC, warmstart=True
    )
    milp_time = time.perf_counter() - t1

    rows.append({
        "Budget": B,
        "GRASP_obj": best_Vg,
        "GRASP_selected": len(best_Sg),
        "GRASP_time_s": grasp_time,
        "MILP_status": status,
        "MILP_obj": Vm,
        "MILP_selected": len(Sm),
        "MILP_time_s": milp_time,
        "Gap_abs": Vm - best_Vg,
    })

df = pd.DataFrame(rows).sort_values("Budget")
df

plt.figure()
plt.plot(df["Budget"], df["GRASP_obj"], marker="o", label="GRASP")
plt.plot(df["Budget"], df["MILP_obj"], marker="o", label="MILP")
plt.xlabel("Budget (INR)")
plt.ylabel("Objective value")
plt.title("Budget vs Objective (<=1 per subgroup)")
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

plt.figure()
plt.plot(df["Budget"], df["GRASP_selected"], marker="o", label="GRASP selected")
plt.plot(df["Budget"], df["MILP_selected"], marker="o", label="MILP selected")
plt.xlabel("Budget (INR)")
plt.ylabel("# practices selected (0 to 5)")
plt.title("Budget vs #Selected (<=1 per subgroup)")
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

# Choose the budget you want to inspect
target_budget = 6000

# Re-solve MILP for that budget to retrieve chosen practices
status, Sm, Vm = solve_milp(
    n, b, w_obj, data.OC, gmat, data.incompat_idx,
    B=target_budget,
    start_S=None,
    subgroup_of=subgroup_of,
    group_names=group_names,
    time_limit=MILP_TIME_LIMIT_SEC,
    warmstart=False
)

print(f"\nSelected practices at budget ₹{target_budget}:\n")
for i in sorted(Sm):
    print(f"- [{group_names[subgroup_of[i]]}] {ids[i]}")