# -*- coding: utf-8 -*-
"""Optimal Allocation 5 practices.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NK9mMdgJS_PZQdLPPjfNA3m__RazO7fC
"""

import pandas as pd

# -----------------------------------------------------------
# Synthetic yield change (ΔY) template
# Units:
#   dY_ton_ha_season: change in yield (ton per ha per season)
#   delta_ton_ha_season: pairwise interaction change in yield if BOTH practices are adopted
# Notes: Illustrative placeholders; tune with literature/field assumptions
# -----------------------------------------------------------

yield_practices = [
    {"id": "P1", "practice": "AWD (Alternate Wetting & Drying)", "dY_ton_ha_season": +0.05,
     "notes": "Often near-neutral; slight gain possible with better water control."},
    {"id": "P2", "practice": "Aerobic rice (mostly non-flooded)", "dY_ton_ha_season": -0.20,
     "notes": "Can reduce yield in some sites due to weeds/water stress if not managed."},
    {"id": "P3", "practice": "DSR (Direct Seeded Rice)", "dY_ton_ha_season": -0.05,
     "notes": "May reduce yield if weeds not controlled; can be neutral with good management."},
    {"id": "P4", "practice": "Straw/residue mgmt", "dY_ton_ha_season": +0.02,
     "notes": "Soil health improvements can slightly improve yield over time (short-run small)."},
    {"id": "P5", "practice": "Biochar application", "dY_ton_ha_season": +0.15,
     "notes": "Often improves soil properties; effect depends on rate/quality."},
]

df_yield = pd.DataFrame(yield_practices)
df_yield.to_csv("rice_practices_YIELD.csv", index=False)
print("Wrote: rice_practices_YIELD.csv")

delta_pairs = [
    ("P1", "P3", +0.03, "AWD+DSR: improved water + establishment can be slightly beneficial if managed."),
    ("P1", "P4", +0.01, "Water mgmt + residue mgmt: minor synergy."),
    ("P1", "P5", +0.02, "Biochar can reduce water stress; small synergy with AWD."),
    ("P2", "P3", -0.05, "Aerobic+DSR: weed pressure/management complexity can reduce yield."),
    ("P2", "P4",  0.00, "Mostly neutral interaction."),
    ("P2", "P5", +0.03, "Biochar may buffer aerobic stress; small help."),
    ("P3", "P4", +0.01, "Residue mgmt can marginally help DSR soils."),
    ("P3", "P5", +0.02, "Biochar improves establishment/soil; slight synergy."),
    ("P4", "P5", +0.05, "Residues to biochar / soil improvement can improve yield together."),
    ("P1", "P2", -0.10, "Conflicting water regimes; yield risk if attempted together (also incompatible)."),
]

df_delta = pd.DataFrame(delta_pairs, columns=["p_i", "p_k", "delta_ton_ha_season", "rationale"])
df_delta.to_csv("rice_delta_pairs.csv", index=False)
print("Wrote: rice_delta_pairs.csv")

import pandas as pd

# -------- CSP data --------
csp_data = [
    ("P1", "AWD", 2.0),
    ("P2", "Aerobic rice", 3.0),
    ("P3", "DSR", 0.8),
    ("P4", "Residue mgmt", 0.7),
    ("P5", "Biochar", 1.5),
]
df_csp = pd.DataFrame(csp_data, columns=["id","practice","CSP_tCO2e_ha_season"])
df_csp.to_csv("rice_practices_CSP.csv", index=False)

# -------- OC data --------
oc_data = [
    ("P1", "AWD", 1200),
    ("P2", "Aerobic rice", 2000),
    ("P3", "DSR", 1500),
    ("P4", "Residue mgmt", 800),
    ("P5", "Biochar", 2500),
]
df_oc = pd.DataFrame(oc_data, columns=["id","practice","OC_INR_ha_season"])
df_oc.to_csv("rice_practices_OC.csv", index=False)

print("Created CSP & OC files")

# -------------------------------
# File paths
# -------------------------------
CSP_FILE = "rice_practices_CSP.csv"
OC_FILE  = "rice_practices_OC.csv"
YIELD_FILE = "rice_practices_YIELD.csv"
DELTA_PAIRS_FILE = "rice_delta_pairs.csv"

# -------------------------------
# Load datasets
# -------------------------------
df_csp = pd.read_csv(CSP_FILE)
df_oc  = pd.read_csv(OC_FILE)
df_y   = pd.read_csv(YIELD_FILE)

# -------------------------------
# Merge CSP + OC
# -------------------------------
df = pd.merge(df_csp, df_oc, on="id", how="inner", suffixes=("_csp", "_oc"))

# -------------------------------
# Add Yield column
# -------------------------------
df = pd.merge(df, df_y[["id", "dY_ton_ha_season"]], on="id", how="inner")

# -------------------------------
# Sort
# -------------------------------
df = df.sort_values("id").reset_index(drop=True)

DY = df["dY_ton_ha_season"].astype(float).tolist()

# Create ID → index mapping
ids = df["id"].tolist()
id_to_idx = {pid: i for i, pid in enumerate(ids)}

df_delta = pd.read_csv(DELTA_PAIRS_FILE)

delta = {}
for _, r in df_delta.iterrows():
    i = id_to_idx[r["p_i"]]
    k = id_to_idx[r["p_k"]]

    if i == k:
        continue

    j, t = (i, k) if i < k else (k, i)
    delta[(j, t)] = float(r["delta_ton_ha_season"])

import os
import pandas as pd

def load_pair_dict_if_exists(path, col_value, id_to_idx, col_i="p_i", col_k="p_k"):
    if not os.path.exists(path):
        print(f"WARNING: {path} not found. Using empty dict.")
        return {}
    dfp = pd.read_csv(path)
    d = {}
    for _, r in dfp.iterrows():
        i = id_to_idx[r[col_i]]
        k = id_to_idx[r[col_k]]
        if i == k:
            continue
        a, b = (i, k) if i < k else (k, i)
        d[(a, b)] = float(r[col_value])
    return d

ALPHA_PAIRS_FILE = "rice_alpha_pairs.csv"
GAMMA_PAIRS_FILE = "rice_gamma_pairs.csv"
DELTA_PAIRS_FILE = "rice_delta_pairs.csv"

alpha = load_pair_dict_if_exists(ALPHA_PAIRS_FILE, "alpha_tco2e_ha_season", id_to_idx)
gamma = load_pair_dict_if_exists(GAMMA_PAIRS_FILE, "gamma_INR_ha_season", id_to_idx)
delta = load_pair_dict_if_exists(DELTA_PAIRS_FILE, "delta_ton_ha_season", id_to_idx)

print("Pairs loaded:", len(alpha), "alpha,", len(gamma), "gamma,", len(delta), "delta")

# MASTER SETUP CELL

import pandas as pd
from itertools import combinations

# Prices
CCP = 1500.0
CROP_PRICE = 22000.0

# Load main data
df_csp = pd.read_csv("rice_practices_CSP.csv")
df_oc  = pd.read_csv("rice_practices_OC.csv")
df_y   = pd.read_csv("rice_practices_YIELD.csv")

df = df_csp.merge(df_oc, on="id").merge(df_y[["id","dY_ton_ha_season"]], on="id")
df = df.sort_values("id").reset_index(drop=True)

# Build arrays
ids = df["id"].tolist()
id_to_idx = {pid:i for i,pid in enumerate(ids)}
m = len(ids)

CSP = df["CSP_tCO2e_ha_season"].tolist()
OC  = df["OC_INR_ha_season"].tolist()
DY  = df["dY_ton_ha_season"].tolist()

# Load delta (yield interactions)
df_delta = pd.read_csv("rice_delta_pairs.csv")
delta = {}
for _, r in df_delta.iterrows():
    i = id_to_idx[r["p_i"]]
    k = id_to_idx[r["p_k"]]
    if i != k:
        j,t = (i,k) if i<k else (k,i)
        delta[(j,t)] = r["delta_ton_ha_season"]

# Optional (if files missing)
alpha = {}
gamma = {}

# ==============================
# GRASP (heuristic) -> MILP (exact) for your 5-practice QKP bundle model
# Drop this cell AFTER your "MASTER SETUP CELL" (where ids, m, CSP, OC, DY,
# alpha, delta, gamma, incompat_idx, CCP, CROP_PRICE are already defined).
# ==============================

import random
from itertools import combinations

# ---- Budget (same as your MILP example) ----
BUDGET_INR = 3500

# ---- Build objective coefficients (same logic as your MILP) ----
def pair_key(i, j):
    return (i, j) if i < j else (j, i)

b_lin = [CCP * CSP[j] + CROP_PRICE * DY[j] - OC[j] for j in range(m)]
pair_list = sorted(set(alpha.keys()) | set(delta.keys()) | set(gamma.keys()))

w_pair_obj = {}
for (j, k) in pair_list:
    w_pair_obj[(j, k)] = (
        CCP * alpha.get((j, k), 0.0)
        + CROP_PRICE * delta.get((j, k), 0.0)
        - gamma.get((j, k), 0.0)
    )

# ---- Feasibility + objective helpers ----
def total_cost(S, OC, gamma):
    """Cost = sum OC + sum gamma pair costs."""
    cost = sum(OC[i] for i in S)
    for a, b in combinations(sorted(S), 2):
        cost += gamma.get(pair_key(a, b), 0.0)
    return cost

def is_feasible_set(S, incompat_idx, B, OC, gamma):
    Sset = set(S)
    for (i, k) in incompat_idx:
        if i in Sset and k in Sset:
            return False
    return total_cost(S, OC, gamma) <= B

def obj_value(S, b_lin, w_pair_obj):
    """Net objective = linear terms + quadratic interaction terms."""
    val = sum(b_lin[i] for i in S)
    for a, b in combinations(sorted(S), 2):
        val += w_pair_obj.get(pair_key(a, b), 0.0)
    return val

# ---- GRASP: randomized greedy construction ----
def grasp_construct(m, incompat_idx, B, OC, gamma, b_lin, w_pair_obj,
                    alpha_rcl=0.3, p_explore=0.10, rng=None):
    """
    Build a feasible solution with a Greedy Randomized (RCL) rule.
    alpha_rcl in [0,1]: smaller = greedier, larger = more random.
    p_explore: if all marginal gains are <=0, occasionally add a random feasible item to explore synergies.
    """
    if rng is None:
        rng = random.Random()

    S = []
    base_obj = obj_value(S, b_lin, w_pair_obj)
    base_cost = total_cost(S, OC, gamma)

    while True:
        candidates = []
        for i in range(m):
            if i in S:
                continue
            S2 = S + [i]
            if not is_feasible_set(S2, incompat_idx, B, OC, gamma):
                continue

            new_obj = obj_value(S2, b_lin, w_pair_obj)
            new_cost = total_cost(S2, OC, gamma)

            marg_gain = new_obj - base_obj
            marg_cost = new_cost - base_cost
            score = marg_gain / (marg_cost if marg_cost > 1e-9 else 1.0)

            candidates.append((i, score, marg_gain))

        if not candidates:
            break

        # Prefer positive-marginal candidates if they exist
        pos = [c for c in candidates if c[2] > 1e-12]
        if pos:
            pool = pos
        else:
            # All are non-positive: stop most of the time, but sometimes explore
            if rng.random() > p_explore:
                break
            pool = candidates  # explore a random feasible move

        scores = [c[1] for c in pool]
        s_max, s_min = max(scores), min(scores)
        cutoff = s_max - alpha_rcl * (s_max - s_min)  # standard RCL threshold
        rcl = [c for c in pool if c[1] >= cutoff]

        i_pick = rng.choice(rcl)[0]
        S.append(i_pick)
        base_obj = obj_value(S, b_lin, w_pair_obj)
        base_cost = total_cost(S, OC, gamma)

    return S

# ---- GRASP: local search (best-improving add/remove/swap) ----
def local_search(S, m, incompat_idx, B, OC, gamma, b_lin, w_pair_obj):
    S = sorted(set(S))
    improved = True

    while improved:
        improved = False
        best_move = None
        best_val = obj_value(S, b_lin, w_pair_obj)

        # 1) Try ADD
        for j in range(m):
            if j in S:
                continue
            S2 = S + [j]
            if not is_feasible_set(S2, incompat_idx, B, OC, gamma):
                continue
            v2 = obj_value(S2, b_lin, w_pair_obj)
            if v2 > best_val + 1e-9:
                best_val = v2
                best_move = ("add", j)

        # 2) Try REMOVE
        for i in list(S):
            S2 = [x for x in S if x != i]
            if not is_feasible_set(S2, incompat_idx, B, OC, gamma):
                continue
            v2 = obj_value(S2, b_lin, w_pair_obj)
            if v2 > best_val + 1e-9:
                best_val = v2
                best_move = ("remove", i)

        # 3) Try SWAP
        Sset = set(S)
        for i in list(S):
            for j in range(m):
                if j in Sset:
                    continue
                S2 = [x for x in S if x != i] + [j]
                if not is_feasible_set(S2, incompat_idx, B, OC, gamma):
                    continue
                v2 = obj_value(S2, b_lin, w_pair_obj)
                if v2 > best_val + 1e-9:
                    best_val = v2
                    best_move = ("swap", i, j)

        if best_move is not None:
            improved = True
            if best_move[0] == "add":
                S.append(best_move[1])
            elif best_move[0] == "remove":
                S = [x for x in S if x != best_move[1]]
            else:  # swap
                _, i, j = best_move
                S = [x for x in S if x != i] + [j]
            S = sorted(set(S))

    return S

def run_grasp(m, incompat_idx, B, OC, gamma, b_lin, w_pair_obj,
             iters=200, alpha_rcl=0.3, p_explore=0.10, seed=42):
    rng = random.Random(seed)
    best_S, best_v = [], float("-inf")

    for _ in range(iters):
        S0 = grasp_construct(
            m, incompat_idx, B, OC, gamma, b_lin, w_pair_obj,
            alpha_rcl=alpha_rcl, p_explore=p_explore, rng=rng
        )
        S1 = local_search(S0, m, incompat_idx, B, OC, gamma, b_lin, w_pair_obj)
        v1 = obj_value(S1, b_lin, w_pair_obj)
        if v1 > best_v:
            best_S, best_v = S1, v1

    return best_S, best_v

# ---- Run GRASP first ----
grasp_S, grasp_val = run_grasp(
    m, incompat_idx, BUDGET_INR, OC, gamma, b_lin, w_pair_obj,
    iters=200, alpha_rcl=0.3, p_explore=0.10, seed=7
)

print("=== GRASP result ===")
print("Budget:", BUDGET_INR)
print("Bundle:", [ids[i] for i in grasp_S] if grasp_S else "∅")
print("Cost:", round(total_cost(grasp_S, OC, gamma), 2))
print("Objective (net value):", round(grasp_val, 2))

# ==============================
# MILP (PuLP) with GRASP warm-start
# ==============================

try:
    import pulp
except ImportError:
    import sys, subprocess
    subprocess.check_call([sys.executable, "-m", "pip", "install", "pulp"])
    import pulp

def solve_milp_bundle_with_warm_start(B, start_S):
    prob = pulp.LpProblem("Rice_Practice_Bundle", pulp.LpMaximize)

    x = {j: pulp.LpVariable(f"x_{j}", cat="Binary") for j in range(m)}
    y = {(j, k): pulp.LpVariable(f"y_{j}_{k}", cat="Binary") for (j, k) in pair_list}

    # Objective
    prob += (
        pulp.lpSum(b_lin[j] * x[j] for j in range(m)) +
        pulp.lpSum(w_pair_obj[(j, k)] * y[(j, k)] for (j, k) in pair_list)
    )

    # Incompatibilities
    for (i, k) in incompat_idx:
        prob += x[i] + x[k] <= 1

    # Linearization: y_jk = x_j * x_k
    for (j, k) in pair_list:
        prob += y[(j, k)] <= x[j]
        prob += y[(j, k)] <= x[k]
        prob += y[(j, k)] >= x[j] + x[k] - 1

    # Budget: sum OC_j x_j + sum gamma_jk y_jk <= B
    prob += (
        pulp.lpSum(OC[j] * x[j] for j in range(m)) +
        pulp.lpSum(gamma.get((j, k), 0.0) * y[(j, k)] for (j, k) in pair_list)
        <= B
    )

    # --- Warm start from GRASP ---
    start_set = set(start_S)
    for j in range(m):
        x[j].setInitialValue(1 if j in start_set else 0)
    for (j, k) in pair_list:
        y[(j, k)].setInitialValue(1 if (j in start_set and k in start_set) else 0)

    # Solve (try warmStart; fall back if solver wrapper doesn't support it)
    try:
        solver = pulp.PULP_CBC_CMD(msg=False, warmStart=True)
    except TypeError:
        solver = pulp.PULP_CBC_CMD(msg=False)

    prob.solve(solver)

    status = pulp.LpStatus[prob.status]
    if status not in ("Optimal", "Not Solved", "Undefined", "Infeasible"):
        raise RuntimeError(f"Unexpected solver status: {status}")

    chosen = [j for j in range(m) if int(pulp.value(x[j])) == 1]
    obj = float(pulp.value(prob.objective))
    return status, chosen, obj

milp_status, milp_S, milp_val = solve_milp_bundle_with_warm_start(BUDGET_INR, grasp_S)

print("\n=== MILP result (warm-started from GRASP) ===")
print("Status:", milp_status)
print("Budget:", BUDGET_INR)
print("Bundle:", [ids[i] for i in milp_S] if milp_S else "∅")
print("Cost:", round(total_cost(milp_S, OC, gamma), 2))
print("Objective (net value):", round(milp_val, 2))

print("\n(Comparison) MILP - GRASP objective gap:", round(milp_val - grasp_val, 6))

b = [CCP * CSP[j] + CROP_PRICE * DY[j] - OC[j] for j in range(m)]

w_pair = {}
pairs = set(alpha.keys()) | set(gamma.keys()) | set(delta.keys())

for (j, k) in pairs:
    w_pair[(j, k)] = (
        CCP * alpha.get((j, k), 0.0)
        + CROP_PRICE * delta.get((j, k), 0.0)
        - gamma.get((j, k), 0.0)
    )

print("m =", m)
print("b (per-practice linear terms):", b)
print("num pair terms:", len(w_pair))

incompat = [("P1","P2")]  # AWD and Aerobic (example)
incompat_idx = [(id_to_idx[a], id_to_idx[b]) for a,b in incompat]

from itertools import product

def is_feasible(x, incompat_idx):
    for (i,k) in incompat_idx:
        if x[i] == 1 and x[k] == 1:
            return False
    return True

best_val = -1e18
best_x = None

for x in product([0,1], repeat=m):
    if not is_feasible(x, incompat_idx):
        continue

    val = sum(b[j] * x[j] for j in range(m))
    for (j,k), wjk in w_pair.items():
        val += wjk * x[j] * x[k]

    if val > best_val:
        best_val = val
        best_x = x

print("Best value:", best_val)
print("Best x*:", best_x)

chosen = [j for j in range(m) if best_x[j] == 1]
C_star = [ids[j] for j in chosen]
print("Selected bundle C*:", C_star)

# compute totals including interactions
V = sum(CSP[j] for j in chosen)
W = sum(OC[j] for j in chosen)
Y = sum(DY[j] for j in chosen)

for a in range(len(chosen)):
    for b2 in range(a+1, len(chosen)):
        j, k = chosen[a], chosen[b2]
        jk = (min(j,k), max(j,k))
        # alpha/gamma might be empty in your notebook; that's okay
        V += alpha.get(jk, 0.0)
        W += gamma.get(jk, 0.0)
        Y += delta.get(jk, 0.0)

net = CCP * V + CROP_PRICE * Y - W

print(f"Total carbon V(C*): {V:.4f} tCO2e/ha/season")
print(f"Total yield ΔY(C*): {Y:.4f} ton/ha/season")
print(f"Total cost W(C*): {W:.2f} INR/ha/season")
print(f"Net value: {net:.2f} INR/ha/season")

def solve_for_price(CCP_value):
    b_local = [CCP_value * CSP[j] + CROP_PRICE * DY[j] - OC[j] for j in range(m)]
    w_local = {}
    pairs = set(alpha.keys()) | set(gamma.keys()) | set(delta.keys())
    for (j,k) in pairs:
        w_local[(j,k)] = CCP_value * alpha.get((j,k),0.0) + CROP_PRICE * delta.get((j,k),0.0) - gamma.get((j,k),0.0)

    best_val = -1e18
    best_x = None
    for x in product([0,1], repeat=m):
        if not is_feasible(x, incompat_idx):
            continue
        val = sum(b_local[j] * x[j] for j in range(m))
        for (j,k), wjk in w_local.items():
            val += wjk * x[j] * x[k]
        if val > best_val:
            best_val, best_x = val, x

    chosen = tuple(ids[j] for j in range(m) if best_x[j] == 1)
    return chosen, best_val

for ptest in [500, 1000, 1500, 2000, 2500]:
    bundle, val = solve_for_price(float(ptest))
    print("CCP =", ptest, "->", bundle, " net =", round(val,2))

# -------------------------------
# Shapley allocation for Yield-extended model
# g(C) = CCP*V(C) + CROP_PRICE*ΔY(C) - W(C)
# Works with interactions: alpha (carbon), delta (yield), gamma (cost)
# -------------------------------

import math
from itertools import combinations

def bundle_components(S, CSP, DY, OC, alpha, delta, gamma):
    """
    Return (V, Y, W) for a subset S of practice indices.
    V: total carbon outcome (incl alpha)
    Y: total yield change (incl delta)
    W: total cost (incl gamma)
    """
    V = sum(CSP[i] for i in S)
    Y = sum(DY[i]  for i in S)
    W = sum(OC[i]  for i in S)

    for a, b in combinations(S, 2):
        jk = (a, b) if a < b else (b, a)
        V += alpha.get(jk, 0.0)
        Y += delta.get(jk, 0.0)
        W += gamma.get(jk, 0.0)

    return V, Y, W

def g_value(S, CCP, CROP_PRICE, CSP, DY, OC, alpha, delta, gamma):
    """
    Characteristic value for subset S (practice indices).
    """
    V, Y, W = bundle_components(S, CSP, DY, OC, alpha, delta, gamma)
    return CCP * V + CROP_PRICE * Y - W

def shapley_values(bundle, CCP, CROP_PRICE, CSP, DY, OC, alpha, delta, gamma):
    """
    Compute Shapley values for practices in 'bundle' (list of indices).
    Uses exact enumeration over all subsets of bundle (OK since bundle small).
    """
    n = len(bundle)
    if n == 0:
        return {}

    # Map local positions 0..n-1 to global practice indices
    players = list(bundle)

    # Precompute factorials for weights
    fact = [math.factorial(i) for i in range(n+1)]
    denom = fact[n]

    phi = {i: 0.0 for i in players}

    # Enumerate subsets S of players not containing i
    # We'll build subsets by size
    for i in players:
        others = [p for p in players if p != i]
        for s in range(0, n):  # size of subset from 0 to n-1
            for S in combinations(others, s):
                S = list(S)
                w = fact[s] * fact[n - s - 1] / denom
                mc = g_value(S + [i], CCP, CROP_PRICE, CSP, DY, OC, alpha, delta, gamma) - \
                     g_value(S,        CCP, CROP_PRICE, CSP, DY, OC, alpha, delta, gamma)
                phi[i] += w * mc

    return phi

# -------------------------------
# Use it on your found optimal solution
# You should already have:
# ids, CCP, CROP_PRICE, CSP, DY, OC, alpha, delta, gamma
# and best_x (or chosen indices)
# -------------------------------

# If you have best_x:
# chosen = [j for j in range(m) if best_x[j] == 1]

# Compute Shapley on chosen bundle
phi_total = shapley_values(chosen, CCP, CROP_PRICE, CSP, DY, OC, alpha, delta, gamma)

# Print results nicely
print("\n--- Shapley allocation over practices in C* (Total Net Value) ---")
total_net = g_value(chosen, CCP, CROP_PRICE, CSP, DY, OC, alpha, delta, gamma)
print("C* =", [ids[i] for i in chosen])
print("Total net g(C*) =", round(total_net, 4))

for i in chosen:
    print(f"{ids[i]}: {phi_total[i]:.4f}")

print("Sum of Shapley =", round(sum(phi_total.values()), 4))

# -------------------------------
# OPTIONAL: Also decompose Shapley into 3 parts (interpretability)
# Carbon revenue part: CCP*V(C)
# Yield revenue part : CROP_PRICE*Y(C)
# Cost part          : -W(C)
# This helps you write Table II style breakdown.
# -------------------------------

def g_carbon(S, CCP, CSP, alpha):
    V = sum(CSP[i] for i in S)
    for a, b in combinations(S, 2):
        jk = (a, b) if a < b else (b, a)
        V += alpha.get(jk, 0.0)
    return CCP * V

def g_yield(S, CROP_PRICE, DY, delta):
    Y = sum(DY[i] for i in S)
    for a, b in combinations(S, 2):
        jk = (a, b) if a < b else (b, a)
        Y += delta.get(jk, 0.0)
    return CROP_PRICE * Y

def g_cost(S, OC, gamma):
    W = sum(OC[i] for i in S)
    for a, b in combinations(S, 2):
        jk = (a, b) if a < b else (b, a)
        W += gamma.get(jk, 0.0)
    return -W  # negative because cost is subtracted

def shapley_generic(bundle, value_fn):
    n = len(bundle)
    fact = [math.factorial(i) for i in range(n+1)]
    denom = fact[n]
    players = list(bundle)
    phi = {i: 0.0 for i in players}

    for i in players:
        others = [p for p in players if p != i]
        for s in range(0, n):
            for S in combinations(others, s):
                S = list(S)
                w = fact[s] * fact[n - s - 1] / denom
                phi[i] += w * (value_fn(S + [i]) - value_fn(S))
    return phi

phi_carbon = shapley_generic(chosen, lambda S: g_carbon(S, CCP, CSP, alpha))
phi_yield  = shapley_generic(chosen, lambda S: g_yield(S, CROP_PRICE, DY, delta))
phi_cost   = shapley_generic(chosen, lambda S: g_cost(S, OC, gamma))

print("\n--- Shapley breakdown (Carbon, Yield, Cost) ---")
for i in chosen:
    print(f"{ids[i]}: carbon={phi_carbon[i]:.2f}, yield={phi_yield[i]:.2f}, cost={phi_cost[i]:.2f}, total={(phi_carbon[i]+phi_yield[i]+phi_cost[i]):.2f}")
print("Check totals:")
print(" sum(carbon) =", round(sum(phi_carbon.values()), 2),
      " sum(yield) =", round(sum(phi_yield.values()), 2),
      " sum(cost)  =", round(sum(phi_cost.values()), 2),
      " sum(total) =", round(sum(phi_carbon.values())+sum(phi_yield.values())+sum(phi_cost.values()), 2))

import numpy as np
import matplotlib.pyplot as plt

# Assumes you already computed these from the Shapley breakdown cell:
# phi_carbon, phi_yield, chosen, ids
# (phi_carbon and phi_yield are in INR/ha/season)

labels = [ids[i] for i in chosen]
carbon_vals = np.array([phi_carbon[i] for i in chosen], dtype=float)
yield_vals  = np.array([phi_yield[i]  for i in chosen], dtype=float)

x = np.arange(len(labels))
width = 0.38

plt.figure()
plt.bar(x - width/2, carbon_vals, width, label="Carbon contribution (INR)")
plt.bar(x + width/2, yield_vals,  width, label="Yield contribution (INR)")

plt.xticks(x, labels)
plt.ylabel("Shapley contribution (INR/ha/season)")
plt.title("Carbon vs Yield Shapley Contributions (for selected bundle C*)")
plt.legend()
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

plt.figure()
bars1 = plt.bar(x - width/2, carbon_vals, width, label="Carbon contribution (INR)")
bars2 = plt.bar(x + width/2, yield_vals,  width, label="Yield contribution (INR)")

for b in list(bars1) + list(bars2):
    h = b.get_height()
    plt.text(b.get_x() + b.get_width()/2, h, f"{h:.0f}", ha="center", va="bottom", fontsize=9)

plt.xticks(x, labels)
plt.ylabel("Shapley contribution (INR/ha/season)")
plt.title("Carbon vs Yield Shapley Contributions (for selected bundle C*)")
plt.legend()
plt.tight_layout()
plt.show()

import numpy as np
import pandas as pd

# m = number of practices
# ids = ['P1','P2','P3','P4','P5']
# delta = {(0,2):0.03, (0,3):0.01, ...}

delta_mat = np.zeros((m, m))

for (j, k), val in delta.items():
    delta_mat[j, k] = val
    delta_mat[k, j] = val   # symmetric

# convert to dataframe for clean printing
delta_df = pd.DataFrame(delta_mat, index=ids, columns=ids)
print(delta_df)

BUDGET_INR = 3500  # INR/ha/season (example)

# ---- Budget sweep & graphs (5 practices, brute force) ----
import itertools
import pandas as pd
import matplotlib.pyplot as plt

# Budgets to evaluate (edit as you like)
BUDGET_GRID = list(range(0, 6001, 50))

def subset_is_feasible(S, incompat_idx, B):
    """S = list of practice indices. Checks incompatibility + budget (cost incl. gamma)."""
    Sset = set(S)

    # incompatibility
    for (i, k) in incompat_idx:
        if i in Sset and k in Sset:
            return False

    # budget: total cost W(S)
    _, _, W = bundle_components(S, CSP, DY, OC, alpha, delta, gamma)
    return W <= B

def solve_for_budget(B):
    """Returns (best_subset_indices, best_net_value, (V,Y,W))."""
    best_val = -1e18
    best_S = []
    best_comp = (0.0, 0.0, 0.0)

    for r in range(m + 1):
        for S in itertools.combinations(range(m), r):
            S = list(S)
            if not subset_is_feasible(S, incompat_idx, B):
                continue

            val = g_value(S, CCP, CROP_PRICE, CSP, DY, OC, alpha, delta, gamma)
            if val > best_val + 1e-9:
                best_val = val
                best_S = S
                best_comp = bundle_components(S, CSP, DY, OC, alpha, delta, gamma)

    return best_S, best_val, best_comp

# Sweep budgets
rows = []
for B in BUDGET_GRID:
    S, net, (V, Y, W) = solve_for_budget(B)
    rows.append({
        "Budget_INR": B,
        "Bundle": ",".join(ids[i] for i in S) if S else "∅",
        "Cost_INR": W,
        "Carbon_tCO2e": V,
        "Yield_ton": Y,
        "Carbon_rev_INR": CCP * V,
        "Yield_rev_INR": CROP_PRICE * Y,
        "Net_value_INR": net,
    })

df_budget = pd.DataFrame(rows)

# Identify bundle change points (for vertical lines)
changes = []
prev = None
for _, r in df_budget.iterrows():
    if r["Bundle"] != prev:
        changes.append((int(r["Budget_INR"]), r["Bundle"]))
        prev = r["Bundle"]

print("Bundle change points (Budget -> Bundle):")
for b, bun in changes:
    print(f"  B={b}: {bun}")

# -------- Graph 1: Optimal net value vs budget --------
plt.figure()
plt.plot(df_budget["Budget_INR"], df_budget["Net_value_INR"])
plt.xlabel("Budget (INR/ha/season)")
plt.ylabel("Optimal net value (INR/ha/season)")
plt.title("Optimal net value vs budget")
for b, _ in changes[1:]:
    plt.axvline(b, linewidth=1)
plt.tight_layout()
plt.savefig("net_value_vs_budget.png", dpi=200)
plt.show()

# -------- Graph 2: Practice inclusion vs budget (step lines) --------
plt.figure()
offset = 1.2
yticks, yticklabels = [], []

for idx, pid in enumerate(ids):
    inc = df_budget["Bundle"].apply(lambda s: 1 if pid in s.split(",") else 0).astype(int)
    y = inc + idx * offset
    plt.plot(df_budget["Budget_INR"], y, drawstyle="steps-post", label=pid)
    yticks.append(idx * offset + 0.5)
    yticklabels.append(pid)

plt.yticks(yticks, yticklabels)
plt.ylim(-0.2, (len(ids) - 1) * offset + 1.4)
plt.xlabel("Budget (INR/ha/season)")
plt.title("Which practices are chosen as budget increases")
plt.tight_layout()
plt.savefig("practice_selection_vs_budget.png", dpi=200)
plt.show()

# -------- Graph 3: Carbon revenue, yield revenue, cost vs budget --------
plt.figure()
plt.plot(df_budget["Budget_INR"], df_budget["Carbon_rev_INR"], label="Carbon revenue")
plt.plot(df_budget["Budget_INR"], df_budget["Yield_rev_INR"], label="Yield revenue")
plt.plot(df_budget["Budget_INR"], df_budget["Cost_INR"], label="Cost")
plt.xlabel("Budget (INR/ha/season)")
plt.ylabel("INR/ha/season")
plt.title("Carbon revenue, yield revenue, and cost (optimal bundle) vs budget")
plt.legend()
plt.tight_layout()
plt.savefig("components_vs_budget.png", dpi=200)
plt.show()

# pip install pulp
import pulp

BUDGET_INR = 3500  # INR/ha/season

def solve_milp_bundle(B):
    # --- rebuild linear coefficients safely (do NOT use variable named `b`) ---
    b_lin = [CCP * CSP[j] + CROP_PRICE * DY[j] - OC[j] for j in range(m)]

    # Pair list: include all pairs that appear in ANY quadratic component
    pair_list = sorted(set(alpha.keys()) | set(delta.keys()) | set(gamma.keys()))
    # NOTE: your objective only uses delta via crop price; alpha & gamma optional
    # Convert those to objective weights:
    w_pair_obj = {}
    for (j,k) in pair_list:
        w_pair_obj[(j,k)] = CCP * alpha.get((j,k), 0.0) + CROP_PRICE * delta.get((j,k), 0.0) - gamma.get((j,k), 0.0)

    prob = pulp.LpProblem("Rice_Practice_Bundle", pulp.LpMaximize)

    # decision vars
    x = {j: pulp.LpVariable(f"x_{j}", cat="Binary") for j in range(m)}
    y = {(j,k): pulp.LpVariable(f"y_{j}_{k}", cat="Binary") for (j,k) in pair_list}

    # Objective
    prob += (
        pulp.lpSum(b_lin[j] * x[j] for j in range(m)) +
        pulp.lpSum(w_pair_obj[(j,k)] * y[(j,k)] for (j,k) in pair_list)
    )

    # Incompatibility
    for (i,k) in incompat_idx:
        prob += x[i] + x[k] <= 1

    # Linearization y_jk = x_j * x_k
    for (j,k) in pair_list:
        prob += y[(j,k)] <= x[j]
        prob += y[(j,k)] <= x[k]
        prob += y[(j,k)] >= x[j] + x[k] - 1

    # Budget: costs include OC + gamma pairs
    prob += (
        pulp.lpSum(OC[j] * x[j] for j in range(m)) +
        pulp.lpSum(gamma.get((j,k), 0.0) * y[(j,k)] for (j,k) in pair_list)
        <= B
    )

    # Solve
    prob.solve(pulp.PULP_CBC_CMD(msg=False))
    status = pulp.LpStatus[prob.status]
    if status != "Optimal":
        raise RuntimeError(f"Solver status: {status}")

    chosen = [j for j in range(m) if int(pulp.value(x[j])) == 1]
    obj = float(pulp.value(prob.objective))
    return chosen, obj

# ---- run once ----
chosen, obj = solve_milp_bundle(BUDGET_INR)
print("Budget:", BUDGET_INR)
print("Chosen bundle:", [ids[j] for j in chosen])
print("Objective (net value):", round(obj, 2))

print("b is:", b, "type:", type(b))

# -------------------------------
# MILP Budget Sweep + 3 Plots
# -------------------------------
# If needed: pip install pulp
import itertools
import pandas as pd
import matplotlib.pyplot as plt
import pulp

# ---- budget grid (edit as needed) ----
BUDGET_GRID = list(range(0, 6001, 50))   # 0..6000 INR, step 50

def solve_milp_bundle(B):
    """
    MILP:
      max sum_j b_j x_j + sum_(j,k) w_jk y_jk
      s.t. incompatibilities, y_jk = x_j*x_k, budget constraint
    """
    # linear term: CCP*CSP + CROP_PRICE*DY - OC
    b_lin = [CCP * CSP[j] + CROP_PRICE * DY[j] - OC[j] for j in range(m)]

    # all pairs that appear anywhere (objective or cost interactions)
    pair_list = sorted(set(alpha.keys()) | set(delta.keys()) | set(gamma.keys()))

    # objective pair coefficient:
    # CCP*alpha + CROP_PRICE*delta - gamma
    w_pair_obj = {}
    for (j, k) in pair_list:
        w_pair_obj[(j, k)] = (
            CCP * alpha.get((j, k), 0.0)
            + CROP_PRICE * delta.get((j, k), 0.0)
            - gamma.get((j, k), 0.0)
        )

    prob = pulp.LpProblem("Rice_Practice_Bundle", pulp.LpMaximize)

    # decision vars
    x = {j: pulp.LpVariable(f"x_{j}", cat="Binary") for j in range(m)}
    y = {(j, k): pulp.LpVariable(f"y_{j}_{k}", cat="Binary") for (j, k) in pair_list}

    # objective
    prob += (
        pulp.lpSum(b_lin[j] * x[j] for j in range(m))
        + pulp.lpSum(w_pair_obj[(j, k)] * y[(j, k)] for (j, k) in pair_list)
    )

    # incompatibilities: x_i + x_k <= 1
    for (i, k) in incompat_idx:
        prob += x[i] + x[k] <= 1

    # linearization: y_jk = x_j * x_k
    for (j, k) in pair_list:
        prob += y[(j, k)] <= x[j]
        prob += y[(j, k)] <= x[k]
        prob += y[(j, k)] >= x[j] + x[k] - 1

    # budget: sum OC_j x_j + sum gamma_jk y_jk <= B
    prob += (
        pulp.lpSum(OC[j] * x[j] for j in range(m))
        + pulp.lpSum(gamma.get((j, k), 0.0) * y[(j, k)] for (j, k) in pair_list)
        <= B
    )

    # solve
    prob.solve(pulp.PULP_CBC_CMD(msg=False))
    status = pulp.LpStatus[prob.status]
    if status != "Optimal":
        raise RuntimeError(f"Solver status: {status}")

    chosen = [j for j in range(m) if int(pulp.value(x[j])) == 1]
    obj = float(pulp.value(prob.objective))
    return chosen, obj

def bundle_components_from_indices(S_idx):
    """Return (V,Y,W) including alpha/delta/gamma pair effects."""
    V = sum(CSP[j] for j in S_idx)
    Y = sum(DY[j] for j in S_idx)
    W = sum(OC[j] for j in S_idx)
    for a, b in itertools.combinations(sorted(S_idx), 2):
        jk = (a, b) if a < b else (b, a)
        V += alpha.get(jk, 0.0)
        Y += delta.get(jk, 0.0)
        W += gamma.get(jk, 0.0)
    return V, Y, W

# ---- sweep budgets ----
rows = []
for B in BUDGET_GRID:
    chosen, net = solve_milp_bundle(B)
    V, Y, W = bundle_components_from_indices(chosen)
    rows.append({
        "Budget_INR": B,
        "Bundle": ",".join(ids[j] for j in chosen) if chosen else "∅",
        "Cost_INR": W,
        "Carbon_tCO2e": V,
        "Yield_ton": Y,
        "Carbon_rev_INR": CCP * V,
        "Yield_rev_INR": CROP_PRICE * Y,
        "Net_value_INR": net,
    })

df_budget = pd.DataFrame(rows)

# ---- bundle change points (for vertical lines) ----
changes = []
prev = None
for _, r in df_budget.iterrows():
    if r["Bundle"] != prev:
        changes.append((int(r["Budget_INR"]), r["Bundle"]))
        prev = r["Bundle"]

print("Bundle change points (Budget -> Bundle):")
for b, bun in changes:
    print(f"  B={b}: {bun}")

# =========================
# Plot 1: Net value vs budget
# =========================
plt.figure()
plt.plot(df_budget["Budget_INR"], df_budget["Net_value_INR"])
plt.xlabel("Budget (INR/ha/season)")
plt.ylabel("Optimal net value (INR/ha/season)")
plt.title("Optimal net value vs budget (MILP)")
for b, _ in changes[1:]:
    plt.axvline(b, linewidth=1)
plt.tight_layout()
plt.savefig("milp_net_value_vs_budget.png", dpi=200)
plt.show()

# ======================================
# Plot 2: Practice selection vs budget
# ======================================
plt.figure()
offset = 1.2
yticks, yticklabels = [], []

for idx, pid in enumerate(ids):
    inc = df_budget["Bundle"].apply(lambda s: 1 if pid in s.split(",") else 0).astype(int)
    y = inc + idx * offset
    plt.plot(df_budget["Budget_INR"], y, drawstyle="steps-post", label=pid)
    yticks.append(idx * offset + 0.5)
    yticklabels.append(pid)

plt.yticks(yticks, yticklabels)
plt.ylim(-0.2, (len(ids) - 1) * offset + 1.4)
plt.xlabel("Budget (INR/ha/season)")
plt.title("Which practices are chosen as budget increases (MILP)")
plt.tight_layout()
plt.savefig("milp_practice_selection_vs_budget.png", dpi=200)
plt.show()

# ======================================
# Plot 3: Components vs budget
# ======================================
plt.figure()
plt.plot(df_budget["Budget_INR"], df_budget["Carbon_rev_INR"], label="Carbon revenue")
plt.plot(df_budget["Budget_INR"], df_budget["Yield_rev_INR"], label="Yield revenue")
plt.plot(df_budget["Budget_INR"], df_budget["Cost_INR"], label="Cost")
plt.xlabel("Budget (INR/ha/season)")
plt.ylabel("INR/ha/season")
plt.title("Carbon revenue, yield revenue, and cost vs budget (MILP)")
plt.legend()
plt.tight_layout()
plt.savefig("milp_components_vs_budget.png", dpi=200)
plt.show()

