# -*- coding: utf-8 -*-
"""optimal 50 practices.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qHOuMLkagHorwd0JykGVuq4mXYcBUNt5
"""

# ============================================================
# 50 Paddy practices: synthesize data + GRASP + warm-start MILP
# Dense mixed-sign pairwise interactions (alpha, delta, gamma)
# ============================================================

from __future__ import annotations
import os, math, random
from dataclasses import dataclass
from itertools import combinations
from typing import Dict, List, Tuple, Set

import pandas as pd

# -----------------------------
# Your 50 practices (exact list)
# -----------------------------
PRACTICES = [
    "Alternate Wetting and Drying (AWD)",
    "AWD using field water-tube monitoring (measured thresholds)",
    "AWD with fewer flooding days (reduced continuous inundation)",
    "Mid-season drainage (MSD)",
    "Early-season drainage (shorten initial flooding period)",
    "Pre-harvest drainage (timely drainage before harvest)",
    "Intermittent irrigation scheduling (fixed wet–dry cycles)",
    "Improved drainage outlets (faster drawdown)",
    "Bund repair + leveling to enable controlled AWD (enables water control)",
    "Laser land leveling (supports uniform AWD / less waterlogging)",
    "Raised beds / furrow-irrigated rice (where applicable)",
    "Aerobic rice management (non-flooded rice system)",
    "Conversion of long-duration flooded rice to shorter-duration rice (less flooding time)",
    "Use of short-duration varieties to reduce flooded period",
    "Shift from transplanted puddled rice to systems reducing puddling/flooding duration (where defined)",
    "Direct-Seeded Rice (DSR) (reduces flooded nursery/puddling period)",
    "Dry seeding (non-puddled establishment)",
    "Reduced puddling intensity (where permitted/defined)",
    "Strip till / reduced till rice establishment (where feasible)",
    "Controlled traffic / minimized soil disturbance (site-dependent)",
    "Improved field channels for precise irrigation (enables AWD)",
    "Timely weeding to maintain aerobic periods (supports AWD feasibility)",
    "Mechanized operations reducing repeated puddling passes (site-dependent)",
    "Optimized N rate (reduce excess N)",
    "Split N application (better timing reduces losses)",
    "Deep placement of urea (UDP)",
    "Controlled-release urea (CRU)",
    "Nitrification inhibitors (where allowed)",
    "Urease inhibitors (where allowed)",
    "Site-Specific Nutrient Management (SSNM)",
    "Leaf Color Chart (LCC)-guided N dosing",
    "Basal N reduction with more top-dressing precision",
    "Balanced fertilization (adequate P/K to reduce excess N needs)",
    "Avoid N application just before heavy irrigation/rain (timing rule)",
    "Replace part of urea with organic sources under planned rates (avoid over-application)",
    "Precision fertilizer application (band placement, calibrated applicators)",
    "Improved manure management timing (avoid anaerobic + N surplus conditions)",
    "Inclusion of legumes in rotation where feasible (reduces synthetic N demand)",
    "No open-field burning of rice straw (avoided emissions)",
    "Straw removal + off-field productive use (with leakage accounted)",
    "Straw composting (instead of burning)",
    "Straw incorporation with drainage/timing to reduce methane spikes (managed incorporation)",
    "Straw mulching under non-flooded/managed water (method-dependent)",
    "Use of straw for bioenergy with accounting (project/method dependent)",
    "Collection/baling systems to prevent burning (enabler for #39)",
    "Biochar application (rice husk/straw biochar)",
    "Compost application (stabilized organic matter)",
    "Farmyard manure application under monitored rates (SOC improvement; method-dependent)",
    "Green manuring (e.g., Sesbania/dhaincha) with proper water management (SOC + N dynamics)",
    "Cover crop/legume in rice fallow (where feasible) to build SOC (rotation-based crediting)",
]

# -----------------------------
# Parameters you can edit
# -----------------------------
SEED = 7

# Economic parameters (same style as your earlier model)
CCP = 1200.0        # INR per tCO2e (carbon credit price)
CROP_PRICE = 22.0   # INR per kg of rice (approx; adjust)

# GRASP settings
GRASP_ITERS = 250
ALPHA_RCL = 0.30
P_EXPLORE = 0.12

# MILP settings
MILP_TIME_LIMIT_SEC = 60  # set None for no limit
USE_WARMSTART = True

# Output folder for CSVs
OUT_DIR = "synthetic_bundle_50"


# ============================================================
# 1) Categorization + exclusivity (logical constraints)
# ============================================================
def classify_practice(name: str) -> Tuple[str, str]:
    s = name.lower()

    # Categories (broad)
    if any(k in s for k in ["awd", "drain", "irrig", "flood", "bund", "laser", "raised beds", "furrow", "aerobic", "channel"]):
        cat = "water"
    elif any(k in s for k in ["direct-seeded", "dsr", "dry seeding", "puddling", "strip till", "reduced till", "controlled traffic", "mechanized", "weeding"]):
        cat = "establishment"
    elif any(k in s for k in ["n rate", "split", "urea", "udp", "cru", "inhibitor", "ssnm", "lcc", "fertiliz", "manure", "legume", "precision fertilizer"]):
        cat = "nitrogen"
    elif any(k in s for k in ["straw", "burn", "mulch", "composting", "bioenergy", "baling", "incorporation"]):
        cat = "residue"
    elif any(k in s for k in ["biochar", "farmyard manure", "green manuring", "cover crop", "soc", "stabilized organic"]):
        cat = "soil"
    else:
        cat = "general"

    # Exclusivity groups (only where it makes sense)
    ex = ""

    # AWD variants: treat as alternative "ways of doing AWD"
    if "awd" in s:
        ex = "awd_variant"

    # Establishment method: you typically pick one primary establishment style
    if any(k in s for k in ["direct-seeded", "dsr", "dry seeding", "reduced puddling", "strip till", "reduced till",
                            "shift from transplanted", "transplanted puddled", "non-puddled"]):
        ex = "establishment_method"

    # Aerobic/raised-bed regime (distinct from AWD-style flooding management)
    if any(k in s for k in ["aerobic rice", "raised beds", "furrow-irrigated"]):
        ex = "aerobic_regime"

    # Duration choice: long-duration -> shorter OR short-duration varieties (treat as alternatives)
    if "short-duration" in s or "long-duration" in s:
        ex = "duration_choice"

    # Residue fate: picking one main straw management pathway (simplification)
    # (baling is an enabler, but we keep it under the same group; you can relax this if you want)
    if "straw" in s or "burn" in s or "bioenergy" in s or "baling" in s:
        ex = "residue_fate"

    return cat, ex


# Base ranges (logical-ish; units per ha per season)
BASE_RANGES = {
    "water":        {"CSP": (0.9, 2.8), "DY": (-140, 240), "OC": (500, 3800)},
    "establishment":{"CSP": (0.3, 1.6), "DY": (-60, 260),  "OC": (600, 4200)},
    "nitrogen":     {"CSP": (0.1, 0.9), "DY": (20, 240),   "OC": (600, 5200)},
    "residue":      {"CSP": (0.4, 1.8), "DY": (-80, 180),  "OC": (400, 3800)},
    "soil":         {"CSP": (0.8, 3.0), "DY": (-20, 220),  "OC": (800, 6500)},
    "general":      {"CSP": (0.2, 1.0), "DY": (-40, 180),  "OC": (700, 4000)},
}

def tri(rng: random.Random, lo: float, hi: float, mode_frac: float) -> float:
    mode = lo + mode_frac * (hi - lo)
    return rng.triangular(lo, hi, mode)

def pair_key(i: int, j: int) -> Tuple[int, int]:
    return (i, j) if i < j else (j, i)


# ============================================================
# 2) Synthetic generation (CSP, OC, DY, alpha, delta, gamma, incompat)
# ============================================================
@dataclass
class BundleData:
    ids: List[str]
    cats: List[str]
    ex_groups: List[str]
    CSP: List[float]
    OC: List[float]
    DY: List[float]
    alpha: Dict[Tuple[int,int], float]
    delta: Dict[Tuple[int,int], float]
    gamma: Dict[Tuple[int,int], float]
    incompat_idx: List[Tuple[int,int]]

def generate_data(practices: List[str], seed: int, out_dir: str) -> BundleData:
    rng = random.Random(seed)
    ids = practices[:]
    n = len(ids)

    cats, ex_groups = [], []
    for nm in ids:
        c, ex = classify_practice(nm)
        cats.append(c)
        ex_groups.append(ex)

    CSP, OC, DY = [], [], []
    for i in range(n):
        r = BASE_RANGES.get(cats[i], BASE_RANGES["general"])
        csp = tri(rng, *r["CSP"], mode_frac=0.62)
        dy  = tri(rng, *r["DY"],  mode_frac=0.55)
        oc  = tri(rng, *r["OC"],  mode_frac=0.58)

        s = ids[i].lower()

        # Practical tweaks for realism
        if cats[i] == "water":
            # AWD/drainage can slightly reduce yield if poorly managed
            if any(k in s for k in ["drain", "awd", "aerobic"]):
                dy += rng.uniform(-50, 30)
            # Laser leveling cost higher
            if "laser" in s:
                oc += rng.uniform(1200, 2200)
                dy += rng.uniform(20, 80)

        if cats[i] == "nitrogen":
            # Inhibitors / CRU / UDP cost more, but yield benefit modest
            if any(k in s for k in ["inhibitor", "controlled-release", "cru", "udp", "deep placement"]):
                oc += rng.uniform(900, 2200)
                dy += rng.uniform(0, 40)
            # LCC/SSNM/precision: moderate cost, good efficiency
            if any(k in s for k in ["lcc", "ssnm", "precision"]):
                dy += rng.uniform(10, 60)

        if cats[i] == "residue":
            # Avoid burning / removal: cost moderate; yield depends
            if "no open-field burning" in s:
                oc += rng.uniform(200, 800)
            if "incorporation" in s:
                dy += rng.uniform(-40, 40)  # could hurt or help
            if "compost" in s:
                dy += rng.uniform(10, 60)

        if cats[i] == "soil":
            if "biochar" in s:
                oc += rng.uniform(1500, 3500)
                csp += rng.uniform(0.3, 0.9)
                dy += rng.uniform(0, 60)
            if "cover crop" in s or "green manuring" in s:
                oc += rng.uniform(500, 1400)
                csp += rng.uniform(0.2, 0.6)

        # Clamp
        csp = max(0.02, min(3.5, csp))
        dy  = max(-400.0, min(600.0, dy))
        oc  = max(150.0, min(9000.0, oc))

        CSP.append(round(csp, 4))
        DY.append(round(dy, 2))
        OC.append(round(oc, 2))

    # Complementarity map (to bias interactions)
    complementary = {
        ("water", "nitrogen"), ("water", "residue"), ("water", "soil"),
        ("nitrogen", "soil"), ("residue", "soil"), ("establishment", "water"),
        ("establishment", "nitrogen"), ("establishment", "water"),
    }
    def is_comp(a: str, b: str) -> bool:
        return (a, b) in complementary or (b, a) in complementary

    alpha: Dict[Tuple[int,int], float] = {}
    delta: Dict[Tuple[int,int], float] = {}
    gamma: Dict[Tuple[int,int], float] = {}

    # Dense interactions: all pairs
    for i, j in combinations(range(n), 2):
        same = (cats[i] == cats[j])
        comp = is_comp(cats[i], cats[j])

        # Mixed-sign core driver
        mu = (0.30 if comp else 0.0) + (-0.22 if same else 0.0)
        z1 = rng.gauss(mu, 0.50)   # for alpha
        z2 = rng.gauss(mu, 0.70)   # for delta
        z3 = rng.gauss((0.18 if same else 0.0) + (-0.08 if comp else 0.0), 0.38)  # for gamma

        # alpha: tCO2e interaction ~ up to 25% of min CSP
        a = (0.25 * min(CSP[i], CSP[j])) * z1
        a = max(-0.80, min(1.00, a))
        alpha[(i, j)] = round(a, 4)

        # delta: kg/ha interaction bounded
        base_y = min(max(abs(DY[i]), 70.0), max(abs(DY[j]), 70.0), 280.0)
        d = (0.25 * base_y) * z2
        d = max(-220.0, min(260.0, d))
        delta[(i, j)] = round(d, 2)

        # gamma: INR/ha interaction bounded (coordination cost or saving)
        g = (0.20 * min(OC[i], OC[j])) * z3
        g = max(-1000.0, min(2200.0, g))
        gamma[(i, j)] = round(g, 2)

    # Incompatibilities:
    incompat: Set[Tuple[int,int]] = set()

    # A) Exclusive groups (all pairs within group are incompatible)
    group_to_items: Dict[str, List[int]] = {}
    for idx, g in enumerate(ex_groups):
        if g:
            group_to_items.setdefault(g, []).append(idx)
    for g, items in group_to_items.items():
        if len(items) >= 2:
            for i, j in combinations(items, 2):
                incompat.add(pair_key(i, j))

    # B) Add a few extra "hard-conflict" pairs (small % of pairs)
    # Score: very negative alpha/delta or very large positive gamma
    all_pairs = list(combinations(range(n), 2))
    def conflict_score(i: int, j: int) -> float:
        a = alpha[(i, j)]
        d = delta[(i, j)] / 200.0
        g = gamma[(i, j)] / 1500.0
        return a + d - g

    ranked = sorted(all_pairs, key=lambda p: conflict_score(p[0], p[1]))
    target_extra = int(0.05 * len(all_pairs))  # ~5% extra conflicts beyond exclusives
    added = 0
    for (i, j) in ranked:
        if added >= target_extra:
            break
        if (i, j) in incompat:
            continue
        if conflict_score(i, j) < -0.60:
            incompat.add((i, j))
            added += 1

    incompat_idx = sorted(incompat)

    # Export CSVs
    os.makedirs(out_dir, exist_ok=True)

    df_pr = pd.DataFrame({
        "idx": list(range(n)),
        "practice": ids,
        "category": cats,
        "exclusive_group": ex_groups,
        "CSP_tCO2e": CSP,
        "OC_INR": OC,
        "dY_kg_per_ha": DY,
    })
    df_pr.to_csv(os.path.join(out_dir, "practices.csv"), index=False)

    df_int = pd.DataFrame([
        {"i": i, "j": j, "alpha": alpha[(i, j)], "delta": delta[(i, j)], "gamma": gamma[(i, j)]}
        for (i, j) in all_pairs
    ])
    df_int.to_csv(os.path.join(out_dir, "interactions.csv"), index=False)

    df_inc = pd.DataFrame([{"i": i, "j": j} for (i, j) in incompat_idx])
    df_inc.to_csv(os.path.join(out_dir, "incompatibilities.csv"), index=False)

    print(f"[OK] Wrote: {out_dir}/practices.csv, interactions.csv, incompatibilities.csv")
    print(f"n={n}, pairs={len(all_pairs)}, incompatibilities={len(incompat_idx)}")
    print("CSP range:", (min(CSP), max(CSP)), "tCO2e")
    print("DY  range:", (min(DY), max(DY)), "kg/ha")
    print("OC  range:", (min(OC), max(OC)), "INR")

    return BundleData(
        ids=ids, cats=cats, ex_groups=ex_groups,
        CSP=CSP, OC=OC, DY=DY,
        alpha=alpha, delta=delta, gamma=gamma,
        incompat_idx=incompat_idx
    )


# ============================================================
# 3) Build objective coefficients for your bundle model
#    Objective: sum b_i x_i + sum w_ij x_i x_j
# ============================================================
def build_objective(data: BundleData, CCP: float, CROP_PRICE: float):
    n = len(data.ids)
    b = [CCP * data.CSP[i] + CROP_PRICE * data.DY[i] - data.OC[i] for i in range(n)]

    # Convert alpha/delta/gamma into one quadratic objective coefficient w_ij
    w = [[0.0] * n for _ in range(n)]
    gmat = [[0.0] * n for _ in range(n)]
    for (i, j), a in data.alpha.items():
        d = data.delta[(i, j)]
        g = data.gamma[(i, j)]
        wij = CCP * a + CROP_PRICE * d - g
        w[i][j] = w[j][i] = float(wij)
        gmat[i][j] = gmat[j][i] = float(g)
    return b, w, gmat


# ============================================================
# 4) GRASP (fast heuristic) using incremental updates
# ============================================================
def build_incompat_sets(n: int, incompat_idx: List[Tuple[int,int]]) -> List[Set[int]]:
    inc = [set() for _ in range(n)]
    for i, j in incompat_idx:
        inc[i].add(j)
        inc[j].add(i)
    return inc

def grasp_solve(n: int, b: List[float], w: List[List[float]], OC: List[float], gmat: List[List[float]],
                incompat: List[Set[int]], B: float,
                iters: int = 200, alpha_rcl: float = 0.3, p_explore: float = 0.10, seed: int = 0):
    rng = random.Random(seed)

    def construct_once():
        inS = [False]*n
        S = []
        sumW = [0.0]*n  # sum of w[i][j] over j in S
        sumG = [0.0]*n  # sum of gamma[i][j] over j in S
        cur_val = 0.0
        cur_cost = 0.0

        while True:
            cand = []
            for i in range(n):
                if inS[i]:
                    continue
                # incompat check
                if any(inS[j] for j in incompat[i]):
                    continue
                add_cost = OC[i] + sumG[i]
                if cur_cost + add_cost > B + 1e-9:
                    continue
                add_gain = b[i] + sumW[i]
                score = add_gain / max(add_cost, 1.0)
                cand.append((i, score, add_gain, add_cost))

            if not cand:
                break

            pos = [c for c in cand if c[2] > 1e-9]
            if pos:
                pool = pos
            else:
                if rng.random() > p_explore:
                    break
                pool = cand

            scores = [c[1] for c in pool]
            smax, smin = max(scores), min(scores)
            cutoff = smax - alpha_rcl*(smax - smin)
            rcl = [c for c in pool if c[1] >= cutoff]
            i = rng.choice(rcl)[0]

            # apply add
            inS[i] = True
            S.append(i)
            cur_val += b[i] + sumW[i]
            cur_cost += OC[i] + sumG[i]
            for k in range(n):
                if k == i:
                    continue
                sumW[k] += w[k][i]
                sumG[k] += gmat[k][i]
        return S

    def local_search(S0: List[int]):
        inS = [False]*n
        for i in S0:
            inS[i] = True

        # build incremental sums
        sumW = [0.0]*n
        sumG = [0.0]*n
        cur_val = 0.0
        cur_cost = 0.0

        for i in range(n):
            if inS[i]:
                cur_val += b[i]
                cur_cost += OC[i]
        for i, j in combinations(range(n), 2):
            if inS[i] and inS[j]:
                cur_val += w[i][j]
                cur_cost += gmat[i][j]
        for i in range(n):
            if not inS[i]:
                # sum over chosen
                sw = 0.0
                sg = 0.0
                for j in range(n):
                    if inS[j]:
                        sw += w[i][j]
                        sg += gmat[i][j]
                sumW[i] = sw
                sumG[i] = sg
            else:
                # sum to other chosen
                sw = 0.0
                sg = 0.0
                for j in range(n):
                    if inS[j] and j != i:
                        sw += w[i][j]
                        sg += gmat[i][j]
                sumW[i] = sw
                sumG[i] = sg

        def feasible_add(x: int, inS_local: List[bool], cost_now: float) -> bool:
            if inS_local[x]:
                return False
            if any(inS_local[j] for j in incompat[x]):
                return False
            return cost_now + (OC[x] + sumG[x]) <= B + 1e-9

        improved = True
        while improved:
            improved = False
            best_gain = 0.0
            best_move = None

            # ADD moves
            for j in range(n):
                if inS[j]:
                    continue
                if not feasible_add(j, inS, cur_cost):
                    continue
                gain = b[j] + sumW[j]
                if gain > best_gain + 1e-9:
                    best_gain = gain
                    best_move = ("add", j)

            # REMOVE moves (useful when item net contribution becomes negative due to interactions)
            for i in range(n):
                if not inS[i]:
                    continue
                gain = -(b[i] + sumW[i])  # removing increases objective if (b+sumW)<0
                if gain > best_gain + 1e-9:
                    best_gain = gain
                    best_move = ("rem", i)

            # SWAP moves
            for i in range(n):
                if not inS[i]:
                    continue
                # after removing i, cost/compat change
                cost_after_rem = cur_cost - (OC[i] + sumG[i])
                for j in range(n):
                    if inS[j]:
                        continue
                    # incompat check against S\{i}
                    if any(inS[k] for k in incompat[j] if k != i):
                        continue
                    add_cost_after = OC[j] + (sumG[j] - gmat[j][i])
                    if cost_after_rem + add_cost_after > B + 1e-9:
                        continue
                    # add gain after removal
                    add_gain_after = b[j] + (sumW[j] - w[j][i])
                    rem_gain = -(b[i] + sumW[i])
                    gain = rem_gain + add_gain_after
                    if gain > best_gain + 1e-9:
                        best_gain = gain
                        best_move = ("swap", i, j)

            if best_move is None:
                break

            improved = True
            typ = best_move[0]

            def apply_remove(i: int):
                nonlocal cur_val, cur_cost
                inS[i] = False
                cur_val -= b[i] + sumW[i]
                cur_cost -= OC[i] + sumG[i]
                for k in range(n):
                    if k == i:
                        continue
                    sumW[k] -= w[k][i]
                    sumG[k] -= gmat[k][i]
                sumW[i] = 0.0
                sumG[i] = 0.0

            def apply_add(j: int):
                nonlocal cur_val, cur_cost
                inS[j] = True
                cur_val += b[j] + sumW[j]
                cur_cost += OC[j] + sumG[j]
                for k in range(n):
                    if k == j:
                        continue
                    sumW[k] += w[k][j]
                    sumG[k] += gmat[k][j]
                # recompute sumW[j],sumG[j] to chosen (excluding itself)
                sw = 0.0
                sg = 0.0
                for k in range(n):
                    if inS[k] and k != j:
                        sw += w[j][k]
                        sg += gmat[j][k]
                sumW[j] = sw
                sumG[j] = sg

            if typ == "add":
                apply_add(best_move[1])
            elif typ == "rem":
                apply_remove(best_move[1])
            else:
                i, j = best_move[1], best_move[2]
                apply_remove(i)
                apply_add(j)

        S_final = [i for i in range(n) if inS[i]]
        return S_final, cur_val, cur_cost

    best_S, best_val, best_cost = [], float("-inf"), 0.0
    for t in range(iters):
        S0 = construct_once()
        S1, v1, c1 = local_search(S0)
        if v1 > best_val:
            best_S, best_val, best_cost = S1, v1, c1

    return best_S, best_val, best_cost


# ============================================================
# 5) MILP (PuLP) warm-started from GRASP (linearization)
# ============================================================
def solve_milp(n: int, b: List[float], w: List[List[float]], OC: List[float], gmat: List[List[float]],
              incompat_idx: List[Tuple[int,int]], B: float, start_S: List[int] | None,
              time_limit: int | None = None, warmstart: bool = True):
    try:
        import pulp
    except ImportError:
        import sys, subprocess
        subprocess.check_call([sys.executable, "-m", "pip", "install", "pulp"])
        import pulp

    prob = pulp.LpProblem("QKP_Bundle", pulp.LpMaximize)

    x = {i: pulp.LpVariable(f"x_{i}", cat="Binary") for i in range(n)}
    pairs = [(i, j) for i in range(n) for j in range(i+1, n)]
    y = {(i, j): pulp.LpVariable(f"y_{i}_{j}", cat="Binary") for (i, j) in pairs}

    # objective
    prob += pulp.lpSum(b[i] * x[i] for i in range(n)) + pulp.lpSum(w[i][j] * y[(i, j)] for (i, j) in pairs)

    # incompatibilities
    for (i, j) in incompat_idx:
        prob += x[i] + x[j] <= 1

    # linearize y_ij = x_i * x_j
    for (i, j) in pairs:
        prob += y[(i, j)] <= x[i]
        prob += y[(i, j)] <= x[j]
        prob += y[(i, j)] >= x[i] + x[j] - 1

    # budget
    prob += pulp.lpSum(OC[i] * x[i] for i in range(n)) + pulp.lpSum(gmat[i][j] * y[(i, j)] for (i, j) in pairs) <= B

    # warm start
    if warmstart and start_S is not None:
        start_set = set(start_S)
        for i in range(n):
            x[i].setInitialValue(1 if i in start_set else 0)
        for (i, j) in pairs:
            y[(i, j)].setInitialValue(1 if (i in start_set and j in start_set) else 0)

    # solve
    # CBC supports timeLimit; warmStart might not always be available in some builds
    solver_kwargs = {"msg": False}
    if time_limit is not None:
        solver_kwargs["timeLimit"] = time_limit
    if warmstart:
        solver_kwargs["warmStart"] = True

    solver = pulp.PULP_CBC_CMD(**solver_kwargs)
    prob.solve(solver)

    status = pulp.LpStatus[prob.status]
    chosen = [i for i in range(n) if int(pulp.value(x[i])) == 1]
    obj = float(pulp.value(prob.objective))
    return status, chosen, obj


# ============================================================
# 6) Run everything
# ============================================================
data = generate_data(PRACTICES, seed=SEED, out_dir=OUT_DIR)
ids = data.ids
n = len(ids)

b, w_obj, gmat = build_objective(data, CCP=CCP, CROP_PRICE=CROP_PRICE)
incompat_sets = build_incompat_sets(n, data.incompat_idx)

# Choose a reasonable default budget (so solution isn't trivial):
# budget ~ sum of cheapest 12 base costs * 1.25 (you can override)
k = 12
sorted_costs = sorted(data.OC)
#BUDGET_INR = 1.25 * sum(sorted_costs[:k])
BUDGET_INR = 3500
print("\nDefault BUDGET_INR (auto):", round(BUDGET_INR, 2), f"(~ {k} cheaper practices * 1.25)")

# --- GRASP ---
Sg, Vg, Cg = grasp_solve(
    n, b, w_obj, data.OC, gmat, incompat_sets, B=BUDGET_INR,
    iters=GRASP_ITERS, alpha_rcl=ALPHA_RCL, p_explore=P_EXPLORE, seed=SEED
)

print("\n=== GRASP result ===")
print("Selected:", len(Sg), "practices")
print("Cost:", round(Cg, 2), " / Budget:", round(BUDGET_INR, 2))
print("Objective:", round(Vg, 2))
print("Bundle:")
for i in sorted(Sg):
    print(f"  - ({i+1:02d}) {ids[i]}")

# --- MILP (warm-started from GRASP) ---
status, Sm, Vm = solve_milp(
    n, b, w_obj, data.OC, gmat, data.incompat_idx, B=BUDGET_INR,
    start_S=Sg, time_limit=MILP_TIME_LIMIT_SEC, warmstart=USE_WARMSTART
)

print("\n=== MILP result (warm-started) ===")
print("Status:", status)
print("Selected:", len(Sm), "practices")
print("Objective:", round(Vm, 2))
print("Bundle:")
for i in sorted(Sm):
    print(f"  - ({i+1:02d}) {ids[i]}")

print("\nObjective gap (MILP - GRASP):", round(Vm - Vg, 6))

import time
import pandas as pd
from itertools import combinations

# ---- helpers to compute cost/objective for any chosen set S ----
def calc_cost(S, OC, gmat):
    S = sorted(S)
    cost = sum(OC[i] for i in S)
    for a, b in combinations(S, 2):
        cost += gmat[a][b]
    return float(cost)

def calc_obj(S, b, w_obj):
    S = sorted(S)
    val = sum(b[i] for i in S)
    for a, c in combinations(S, 2):
        val += w_obj[a][c]
    return float(val)

# ---- choose budgets to test ----
# Use your auto budget as baseline (recompute it the same way)
k = 12
sorted_costs = sorted(data.OC)
B_AUTO = 1.25 * sum(sorted_costs[:k])

# Example: sweep from 50% to 110% of auto budget (13 points)
budget_fracs = [0.50, 0.55, 0.60, 0.65, 0.70, 0.75, 0.80, 0.85, 0.90, 0.95, 1.00, 1.05, 1.10]
budgets = [round(B_AUTO * f, 2) for f in budget_fracs]
print("Budgets:", budgets)

# ---- GRASP settings (try multiple seeds and keep best) ----
GRASP_SEEDS = [1, 7, 11, 21, 42]   # more seeds = more robust
GRASP_ITERS_LOCAL = 200            # per seed

# ---- MILP settings ----
MILP_TL = 30   # seconds per budget (increase if you want); or set None for no limit

rows = []

for B in budgets:
    # ---------- GRASP (best-of-seeds) ----------
    t0 = time.perf_counter()
    best_Sg, best_Vg, best_Cg = [], float("-inf"), 0.0

    for sd in GRASP_SEEDS:
        Sg, Vg, Cg = grasp_solve(
            n, b, w_obj, data.OC, gmat, incompat_sets, B=B,
            iters=GRASP_ITERS_LOCAL, alpha_rcl=ALPHA_RCL, p_explore=P_EXPLORE, seed=sd
        )
        if Vg > best_Vg:
            best_Sg, best_Vg, best_Cg = Sg, Vg, Cg

    grasp_time = time.perf_counter() - t0

    # ---------- MILP ----------
    t1 = time.perf_counter()
    status, Sm, Vm = solve_milp(
        n, b, w_obj, data.OC, gmat, data.incompat_idx, B=B,
        start_S=best_Sg, time_limit=MILP_TL, warmstart=True
    )
    milp_time = time.perf_counter() - t1

    Cm = calc_cost(Sm, data.OC, gmat)

    # Gap (absolute and percent)
    gap_abs = Vm - best_Vg
    gap_pct = (gap_abs / abs(Vm) * 100.0) if abs(Vm) > 1e-9 else 0.0

    rows.append({
        "Budget": B,
        "GRASP_obj": round(best_Vg, 4),
        "GRASP_cost": round(best_Cg, 2),
        "GRASP_selected": len(best_Sg),
        "GRASP_time_s": round(grasp_time, 3),

        "MILP_status": status,
        "MILP_obj": round(Vm, 4),
        "MILP_cost": round(Cm, 2),
        "MILP_selected": len(Sm),
        "MILP_time_s": round(milp_time, 3),

        "Gap_abs(MILP-GRASP)": round(gap_abs, 6),
        "Gap_pct": round(gap_pct, 4),
    })

df = pd.DataFrame(rows)
df

import matplotlib.pyplot as plt

# If you saved results and restarted, uncomment:
# import pandas as pd
# df = pd.read_csv("budget_sweep_results.csv")

# Sort by budget (important for a clean line plot)
df_plot = df.sort_values("Budget")

plt.figure()
plt.plot(df_plot["Budget"], df_plot["GRASP_obj"], marker="o", label="GRASP")
plt.plot(df_plot["Budget"], df_plot["MILP_obj"], marker="o", label="MILP")
plt.xlabel("Budget (INR)")
plt.ylabel("Objective value")
plt.title("Budget vs Objective (GRASP vs MILP)")
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()