# -*- coding: utf-8 -*-
"""farmers_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UQcKexElXFVqXB1j_wT6XtB1hXb5oMGT
"""

# farmers_generator.py
# Generates farmers.csv for SALM / carbon-coalition experiments
#
# Spec (editable):
# - n farmers
# - farm size ~ Lognormal(mu, sigma), truncated to [min_ha, max_ha], rounded
# - budget proportional to size: (budget_per_ha * (1 ± noise)) * size
#
# Output columns:
# Farmer_ID, Farm_Size_ha, Budget_per_ha_INR_per_season, Budget_total_INR_per_season

import numpy as np
import pandas as pd
from pathlib import Path


def truncated_lognormal(
    rng: np.random.Generator,
    n: int,
    mu: float,
    sigma: float,
    low: float,
    high: float,
    round_decimals: int = 2,
    batch_size: int = 10000,
) -> np.ndarray:
    """Sample n values from Lognormal(mu, sigma), truncated to [low, high]."""
    vals = []
    while len(vals) < n:
        x = rng.lognormal(mean=mu, sigma=sigma, size=batch_size)
        x = x[(x >= low) & (x <= high)]
        vals.extend(x.tolist())

    x = np.array(vals[:n])
    x = np.round(x, round_decimals)
    # guardrail after rounding
    x = np.clip(x, low, high)
    x = np.round(x, round_decimals)
    return x


def generate_farmers_df(
    n_farmers: int = 15,
    seed: int = 42,
    mu: float = -0.5,
    sigma: float = 1.0,
    min_ha: float = 0.20,
    max_ha: float = 2.00,
    round_decimals: int = 2,
    budget_per_ha: float = 3500.0,          # INR/ha/season
    budget_noise_pct: float = 0.20,         # ±10%
) -> pd.DataFrame:
    """Return a farmers DataFrame with farm size + budget."""
    rng = np.random.default_rng(seed)

    farm_size = truncated_lognormal(
        rng=rng,
        n=n_farmers,
        mu=mu,
        sigma=sigma,
        low=min_ha,
        high=max_ha,
        round_decimals=round_decimals,
    )

    # Budget per ha with uniform ±noise
    noise = rng.uniform(-budget_noise_pct, budget_noise_pct, size=n_farmers)
    budget_per_ha_realized = budget_per_ha * (1.0 + noise)
    budget_total = farm_size * budget_per_ha_realized

    df = pd.DataFrame({
        "Farmer_ID": [f"F{i+1:04d}" for i in range(n_farmers)],
        "Farm_Size_ha": farm_size,
        "Budget_per_ha_INR_per_season": np.round(budget_per_ha_realized, 2),
        "Budget_total_INR_per_season": np.round(budget_total, 2),
    })

    return df


def main():
    # ---- Edit parameters here if needed ----
    params = dict(
        n_farmers=25,
        seed=42,
        mu=-0.5,
        sigma=1.0,
        min_ha=0.20,
        max_ha=2.00,
        round_decimals=2,
        budget_per_ha=3500.0,
        budget_noise_pct=0.20,
    )

    out_dir = Path("synthetic_salm_data")
    out_dir.mkdir(parents=True, exist_ok=True)

    df = generate_farmers_df(**params)

    out_path = out_dir / "farmers.csv"
    df.to_csv(out_path, index=False)

    print(f"Saved: {out_path.resolve()}")
    print("\nFarm size summary (ha):")
    print(df["Farm_Size_ha"].describe().round(3))
    print("\nBudget total summary (INR/season):")
    print(df["Budget_total_INR_per_season"].describe().round(2))


if __name__ == "__main__":
    main()